require("dotenv").config();
const mongoose = require("mongoose");
const bcrypt = require("bcryptjs");
const config = require("../config");
const { Tenant, User, Category, Product, Order } = require("../models");

const MONGODB_URI = process.env.MONGODB_URI || "mongodb://localhost:27018/retailx";

// Enterprise-level product data
const storeData = [
  {
    name: "Urban Fashion",
    slug: "urban-fashion",
    description: "Premium fashion destination for trendy clothing, accessories, and lifestyle products",
    industry: "fashion",
    owner: {
      email: "owner@urbanfashion.com",
      password: "Owner@123456",
      firstName: "Sarah",
      lastName: "Mitchell",
    },
    branding: {
      primaryColor: "#6366f1",
      secondaryColor: "#4f46e5",
      accentColor: "#f59e0b",
    },
    categories: [
      { name: "Men's Fashion", slug: "mens-fashion", image: "https://images.unsplash.com/photo-1617137968427-85924c800a22?w=400" },
      { name: "Women's Fashion", slug: "womens-fashion", image: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=400" },
      { name: "Accessories", slug: "accessories", image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400" },
      { name: "Footwear", slug: "footwear", image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400" },
      { name: "Watches & Jewelry", slug: "watches-jewelry", image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400" },
      { name: "Sportswear", slug: "sportswear", image: "https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=400" },
    ],
    products: [
      // Men's Fashion - 10 products
      {
        name: "Premium Slim Fit Suit",
        category: "mens-fashion",
        price: 599.99,
        salePrice: 499.99,
        rating: 4.8,
        reviews: 234,
        stock: 45,
        sku: "MF-SUIT-001",
        brand: "Hugo Boss",
        featured: true,
        images: ["https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600", "https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=600"],
        description: "Elevate your professional wardrobe with this impeccably tailored slim fit suit. Crafted from premium Italian wool blend fabric, featuring a modern silhouette with notch lapels and a two-button closure.",
        variants: [
          { name: "Size", values: ["38R", "40R", "42R", "44R", "46R"] },
          { name: "Color", values: ["Navy Blue", "Charcoal", "Black"] },
        ],
      },
      {
        name: "Oxford Cotton Dress Shirt",
        category: "mens-fashion",
        price: 99.99,
        salePrice: 79.99,
        rating: 4.6,
        reviews: 567,
        stock: 200,
        sku: "MF-SHIRT-001",
        brand: "Ralph Lauren",
        images: ["https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600"],
        description: "Classic Oxford cotton dress shirt with a button-down collar. Perfect for both business and casual occasions.",
        variants: [
          { name: "Size", values: ["S", "M", "L", "XL", "XXL"] },
          { name: "Color", values: ["White", "Light Blue", "Pink", "Striped"] },
        ],
      },
      {
        name: "Genuine Leather Belt",
        category: "mens-fashion",
        price: 159.99,
        salePrice: 129.99,
        rating: 4.7,
        reviews: 189,
        stock: 150,
        sku: "MF-BELT-001",
        brand: "Gucci",
        images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600"],
        description: "Genuine Italian leather belt with signature buckle design.",
        variants: [
          { name: "Size", values: ["32", "34", "36", "38", "40"] },
          { name: "Color", values: ["Black", "Brown", "Tan"] },
        ],
      },
      {
        name: "Cashmere V-Neck Sweater",
        category: "mens-fashion",
        price: 299.99,
        salePrice: 249.99,
        rating: 4.9,
        reviews: 156,
        stock: 80,
        sku: "MF-SWTR-001",
        brand: "Loro Piana",
        featured: true,
        images: ["https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600"],
        description: "Luxuriously soft 100% cashmere sweater. Timeless elegance for any occasion.",
        variants: [
          { name: "Size", values: ["S", "M", "L", "XL"] },
          { name: "Color", values: ["Navy", "Burgundy", "Camel", "Grey"] },
        ],
      },
      {
        name: "Tailored Chino Pants",
        category: "mens-fashion",
        price: 119.99,
        salePrice: 89.99,
        rating: 4.5,
        reviews: 423,
        stock: 300,
        sku: "MF-CHINO-001",
        brand: "Dockers",
        images: ["https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600"],
        description: "Modern fit chino pants with stretch comfort technology.",
        variants: [
          { name: "Size", values: ["30x30", "32x30", "32x32", "34x32", "36x32"] },
          { name: "Color", values: ["Khaki", "Navy", "Olive", "Grey"] },
        ],
      },
      {
        name: "Premium Denim Jeans",
        category: "mens-fashion",
        price: 189.99,
        salePrice: 149.99,
        rating: 4.7,
        reviews: 789,
        stock: 250,
        sku: "MF-JEANS-001",
        brand: "Levi's",
        images: ["https://images.unsplash.com/photo-1542272604-787c3835535d?w=600"],
        description: "Classic 501 original fit jeans with authentic vintage wash.",
        variants: [
          { name: "Size", values: ["30", "32", "34", "36", "38"] },
          { name: "Wash", values: ["Dark Indigo", "Medium Wash", "Light Wash", "Black"] },
        ],
      },
      {
        name: "Wool Overcoat",
        category: "mens-fashion",
        price: 449.99,
        salePrice: 379.99,
        rating: 4.8,
        reviews: 112,
        stock: 60,
        sku: "MF-COAT-001",
        brand: "Burberry",
        featured: true,
        images: ["https://images.unsplash.com/photo-1544923246-77307dd628b6?w=600"],
        description: "Classic wool overcoat with timeless British styling.",
        variants: [
          { name: "Size", values: ["S", "M", "L", "XL"] },
          { name: "Color", values: ["Camel", "Navy", "Charcoal"] },
        ],
      },
      {
        name: "Linen Summer Shirt",
        category: "mens-fashion",
        price: 89.99,
        salePrice: 69.99,
        rating: 4.4,
        reviews: 234,
        stock: 180,
        sku: "MF-LINEN-001",
        brand: "Tommy Bahama",
        images: ["https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600"],
        description: "Breathable 100% linen shirt perfect for warm weather.",
        variants: [
          { name: "Size", values: ["S", "M", "L", "XL", "XXL"] },
          { name: "Color", values: ["White", "Sky Blue", "Sage", "Coral"] },
        ],
      },
      {
        name: "Merino Wool Polo",
        category: "mens-fashion",
        price: 129.99,
        salePrice: 99.99,
        rating: 4.6,
        reviews: 345,
        stock: 220,
        sku: "MF-POLO-001",
        brand: "Lacoste",
        images: ["https://images.unsplash.com/photo-1625910513413-5fc45e80b77c?w=600"],
        description: "Premium merino wool polo with classic fit.",
        variants: [
          { name: "Size", values: ["S", "M", "L", "XL"] },
          { name: "Color", values: ["Black", "White", "Navy", "Green"] },
        ],
      },
      {
        name: "Cotton Boxer Brief Set",
        category: "mens-fashion",
        price: 49.99,
        salePrice: 39.99,
        rating: 4.5,
        reviews: 678,
        stock: 400,
        sku: "MF-BOXER-001",
        brand: "Calvin Klein",
        images: ["https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600"],
        description: "3-pack premium cotton boxer briefs with comfort waistband.",
        variants: [{ name: "Size", values: ["S", "M", "L", "XL"] }],
      },

      // Women's Fashion - 10 products
      {
        name: "Designer Evening Gown",
        category: "womens-fashion",
        price: 1299.99,
        salePrice: 899.99,
        rating: 4.9,
        reviews: 89,
        stock: 25,
        sku: "WF-GOWN-001",
        brand: "Vera Wang",
        featured: true,
        images: ["https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600"],
        description: "Stunning floor-length evening gown with intricate beadwork and a flowing silhouette.",
        variants: [
          { name: "Size", values: ["XS", "S", "M", "L", "XL"] },
          { name: "Color", values: ["Midnight Blue", "Burgundy", "Emerald", "Black"] },
        ],
      },
      {
        name: "Silk Blouse Collection",
        category: "womens-fashion",
        price: 229.99,
        salePrice: 179.99,
        rating: 4.7,
        reviews: 345,
        stock: 120,
        sku: "WF-BLOUSE-001",
        brand: "Equipment",
        images: ["https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=600"],
        description: "100% mulberry silk blouse with a relaxed fit and elegant drape.",
        variants: [
          { name: "Size", values: ["XS", "S", "M", "L", "XL"] },
          { name: "Color", values: ["Ivory", "Blush", "Navy", "Black"] },
        ],
      },
      {
        name: "High-Waisted Trousers",
        category: "womens-fashion",
        price: 149.99,
        salePrice: 119.99,
        rating: 4.6,
        reviews: 267,
        stock: 180,
        sku: "WF-TROUSER-001",
        brand: "Theory",
        images: ["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=600"],
        description: "Sophisticated high-waisted trousers with a flattering wide-leg silhouette.",
        variants: [
          { name: "Size", values: ["0", "2", "4", "6", "8", "10", "12"] },
          { name: "Color", values: ["Black", "Navy", "Camel", "Grey"] },
        ],
      },
      {
        name: "Cashmere Wrap Cardigan",
        category: "womens-fashion",
        price: 399.99,
        salePrice: 329.99,
        rating: 4.8,
        reviews: 178,
        stock: 60,
        sku: "WF-CARD-001",
        brand: "Eileen Fisher",
        featured: true,
        images: ["https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600"],
        description: "Luxurious cashmere wrap cardigan for effortless layering.",
        variants: [
          { name: "Size", values: ["XS/S", "M/L", "XL/XXL"] },
          { name: "Color", values: ["Oatmeal", "Charcoal", "Blush", "Navy"] },
        ],
      },
      {
        name: "Designer Leather Handbag",
        category: "womens-fashion",
        price: 1599.99,
        salePrice: 1299.99,
        rating: 4.9,
        reviews: 456,
        stock: 35,
        sku: "WF-BAG-001",
        brand: "Michael Kors",
        featured: true,
        images: ["https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600"],
        description: "Iconic designer handbag crafted from premium Saffiano leather.",
        variants: [{ name: "Color", values: ["Black", "Tan", "Red", "Navy"] }],
      },
      {
        name: "Midi Wrap Dress",
        category: "womens-fashion",
        price: 199.99,
        salePrice: 159.99,
        rating: 4.7,
        reviews: 534,
        stock: 200,
        sku: "WF-DRESS-001",
        brand: "Diane von Furstenberg",
        images: ["https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600"],
        description: "Classic wrap dress with a flattering V-neckline and midi length.",
        variants: [
          { name: "Size", values: ["XS", "S", "M", "L", "XL"] },
          { name: "Pattern", values: ["Solid Black", "Floral", "Geometric", "Animal Print"] },
        ],
      },
      {
        name: "Wool Blazer",
        category: "womens-fashion",
        price: 349.99,
        salePrice: 279.99,
        rating: 4.6,
        reviews: 198,
        stock: 90,
        sku: "WF-BLAZER-001",
        brand: "J.Crew",
        images: ["https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=600"],
        description: "Tailored wool blazer with a modern feminine silhouette.",
        variants: [
          { name: "Size", values: ["0", "2", "4", "6", "8", "10"] },
          { name: "Color", values: ["Black", "Navy", "Camel"] },
        ],
      },
      {
        name: "Silk Midi Skirt",
        category: "womens-fashion",
        price: 179.99,
        salePrice: 139.99,
        rating: 4.5,
        reviews: 223,
        stock: 140,
        sku: "WF-SKIRT-001",
        brand: "Reformation",
        images: ["https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600"],
        description: "Elegant silk midi skirt with bias cut for beautiful draping.",
        variants: [
          { name: "Size", values: ["XS", "S", "M", "L"] },
          { name: "Color", values: ["Champagne", "Black", "Emerald", "Blush"] },
        ],
      },
      {
        name: "Cashmere Turtleneck",
        category: "womens-fashion",
        price: 279.99,
        salePrice: 229.99,
        rating: 4.8,
        reviews: 167,
        stock: 75,
        sku: "WF-TURTLE-001",
        brand: "Everlane",
        images: ["https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600"],
        description: "Ultra-soft cashmere turtleneck sweater in a relaxed fit.",
        variants: [
          { name: "Size", values: ["XS", "S", "M", "L", "XL"] },
          { name: "Color", values: ["Ivory", "Black", "Camel", "Grey"] },
        ],
      },
      {
        name: "Leather Pencil Skirt",
        category: "womens-fashion",
        price: 259.99,
        salePrice: 199.99,
        rating: 4.6,
        reviews: 145,
        stock: 65,
        sku: "WF-LSKIRT-001",
        brand: "AllSaints",
        images: ["https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=600"],
        description: "Genuine leather pencil skirt with back zip closure.",
        variants: [
          { name: "Size", values: ["0", "2", "4", "6", "8", "10"] },
          { name: "Color", values: ["Black", "Brown", "Burgundy"] },
        ],
      },

      // Accessories - 8 products
      {
        name: "Italian Leather Wallet",
        category: "accessories",
        price: 189.99,
        salePrice: 149.99,
        rating: 4.8,
        reviews: 678,
        stock: 300,
        sku: "AC-WALLET-001",
        brand: "Montblanc",
        images: ["https://images.unsplash.com/photo-1627123424574-724758594e93?w=600"],
        description: "Handcrafted Italian leather bifold wallet with RFID protection.",
        variants: [{ name: "Color", values: ["Black", "Brown", "Navy"] }],
      },
      {
        name: "Silk Scarf Collection",
        category: "accessories",
        price: 249.99,
        salePrice: 199.99,
        rating: 4.7,
        reviews: 234,
        stock: 150,
        sku: "AC-SCARF-001",
        brand: "Hermès",
        images: ["https://images.unsplash.com/photo-1601370690183-1c7796ecec61?w=600"],
        description: "100% silk twill scarf with hand-rolled edges and vibrant prints.",
        variants: [{ name: "Pattern", values: ["Classic", "Floral", "Geometric", "Abstract"] }],
      },
      {
        name: "Designer Sunglasses",
        category: "accessories",
        price: 349.99,
        salePrice: 279.99,
        rating: 4.6,
        reviews: 456,
        stock: 200,
        sku: "AC-SUNGLASS-001",
        brand: "Ray-Ban",
        featured: true,
        images: ["https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600"],
        description: "Iconic aviator sunglasses with polarized lenses and gold frame.",
        variants: [{ name: "Lens", values: ["Green Classic", "Brown Gradient", "Blue Mirror"] }],
      },
      {
        name: "Premium Tie Set",
        category: "accessories",
        price: 119.99,
        salePrice: 89.99,
        rating: 4.5,
        reviews: 189,
        stock: 250,
        sku: "AC-TIE-001",
        brand: "Brooks Brothers",
        images: ["https://images.unsplash.com/photo-1589756823695-278bc923f962?w=600"],
        description: "Silk tie and pocket square set in coordinating patterns.",
        variants: [{ name: "Pattern", values: ["Solid", "Striped", "Paisley", "Geometric"] }],
      },
      {
        name: "Leather Gloves",
        category: "accessories",
        price: 129.99,
        salePrice: 99.99,
        rating: 4.7,
        reviews: 156,
        stock: 180,
        sku: "AC-GLOVES-001",
        brand: "Dents",
        images: ["https://images.unsplash.com/photo-1531163002006-6c51b8b0c5d8?w=600"],
        description: "Premium leather gloves with cashmere lining.",
        variants: [
          { name: "Size", values: ["S", "M", "L", "XL"] },
          { name: "Color", values: ["Black", "Brown", "Cognac"] },
        ],
      },
      {
        name: "Canvas Tote Bag",
        category: "accessories",
        price: 89.99,
        salePrice: 69.99,
        rating: 4.4,
        reviews: 345,
        stock: 400,
        sku: "AC-TOTE-001",
        brand: "L.L.Bean",
        images: ["https://images.unsplash.com/photo-1544816155-12df9643f363?w=600"],
        description: "Durable canvas tote with leather handles and monogram option.",
        variants: [
          { name: "Size", values: ["Small", "Medium", "Large"] },
          { name: "Color", values: ["Natural", "Navy", "Red", "Green"] },
        ],
      },
      {
        name: "Cashmere Beanie",
        category: "accessories",
        price: 79.99,
        salePrice: 59.99,
        rating: 4.6,
        reviews: 278,
        stock: 220,
        sku: "AC-BEANIE-001",
        brand: "J.Crew",
        images: ["https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?w=600"],
        description: "Ultra-soft 100% cashmere beanie for cold weather.",
        variants: [{ name: "Color", values: ["Black", "Grey", "Navy", "Burgundy", "Camel"] }],
      },
      {
        name: "Leather Card Holder",
        category: "accessories",
        price: 59.99,
        salePrice: 49.99,
        rating: 4.5,
        reviews: 567,
        stock: 350,
        sku: "AC-CARD-001",
        brand: "Coach",
        images: ["https://images.unsplash.com/photo-1627123424574-724758594e93?w=600"],
        description: "Slim leather card holder with RFID blocking technology.",
        variants: [{ name: "Color", values: ["Black", "Brown", "Navy", "Burgundy"] }],
      },

      // Footwear - 8 products
      {
        name: "Italian Leather Oxfords",
        category: "footwear",
        price: 449.99,
        salePrice: 349.99,
        rating: 4.9,
        reviews: 234,
        stock: 80,
        sku: "FW-OXFORD-001",
        brand: "Allen Edmonds",
        featured: true,
        images: ["https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=600"],
        description: "Handcrafted Italian leather Oxford shoes with Goodyear welt construction.",
        variants: [
          { name: "Size", values: ["7", "8", "9", "10", "11", "12", "13"] },
          { name: "Width", values: ["D (Medium)", "E (Wide)", "EE (Extra Wide)"] },
        ],
      },
      {
        name: "Designer Stiletto Heels",
        category: "footwear",
        price: 850.0,
        salePrice: 695.0,
        rating: 4.8,
        reviews: 156,
        stock: 45,
        sku: "FW-HEELS-001",
        brand: "Jimmy Choo",
        featured: true,
        images: ["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600"],
        description: "Elegant stiletto heels with signature pointed toe and crystal embellishments.",
        variants: [
          { name: "Size", values: ["5", "6", "7", "8", "9", "10"] },
          { name: "Color", values: ["Black", "Nude", "Red", "Silver"] },
        ],
      },
      {
        name: "Premium Leather Sneakers",
        category: "footwear",
        price: 229.99,
        salePrice: 189.99,
        rating: 4.7,
        reviews: 1234,
        stock: 400,
        sku: "FW-SNKR-001",
        brand: "Common Projects",
        images: ["https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600"],
        description: "Minimalist leather sneakers handmade in Italy with gold foil serial number.",
        variants: [
          { name: "Size", values: ["6", "7", "8", "9", "10", "11", "12"] },
          { name: "Color", values: ["White", "Black", "Grey", "Navy"] },
        ],
      },
      {
        name: "Leather Chelsea Boots",
        category: "footwear",
        price: 349.99,
        salePrice: 279.99,
        rating: 4.8,
        reviews: 345,
        stock: 120,
        sku: "FW-CHELSEA-001",
        brand: "R.M. Williams",
        images: ["https://images.unsplash.com/photo-1638247025967-b4e38f787b76?w=600"],
        description: "Classic Chelsea boots crafted from a single piece of leather.",
        variants: [
          { name: "Size", values: ["7", "8", "9", "10", "11", "12"] },
          { name: "Color", values: ["Black", "Chestnut", "Dark Brown"] },
        ],
      },
      {
        name: "Suede Loafers",
        category: "footwear",
        price: 199.99,
        salePrice: 159.99,
        rating: 4.6,
        reviews: 289,
        stock: 160,
        sku: "FW-LOAFER-001",
        brand: "Tod's",
        images: ["https://images.unsplash.com/photo-1582897085656-c636d006a246?w=600"],
        description: "Italian suede penny loafers with leather sole.",
        variants: [
          { name: "Size", values: ["7", "8", "9", "10", "11", "12"] },
          { name: "Color", values: ["Navy", "Brown", "Tan", "Black"] },
        ],
      },
      {
        name: "Athletic Running Shoes",
        category: "footwear",
        price: 179.99,
        salePrice: 149.99,
        rating: 4.7,
        reviews: 892,
        stock: 350,
        sku: "FW-RUN-001",
        brand: "Nike",
        images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600"],
        description: "Lightweight running shoes with responsive foam cushioning.",
        variants: [
          { name: "Size", values: ["6", "7", "8", "9", "10", "11", "12", "13"] },
          { name: "Color", values: ["Black/White", "Grey/Volt", "Navy/Orange"] },
        ],
      },
      {
        name: "Leather Ankle Boots",
        category: "footwear",
        price: 295.0,
        salePrice: 245.0,
        rating: 4.7,
        reviews: 198,
        stock: 85,
        sku: "FW-ANKLE-001",
        brand: "Rag & Bone",
        images: ["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600"],
        description: "Modern ankle boots with block heel and side zip.",
        variants: [
          { name: "Size", values: ["5", "6", "7", "8", "9", "10"] },
          { name: "Color", values: ["Black", "Cognac", "Taupe"] },
        ],
      },
      {
        name: "Canvas Espadrilles",
        category: "footwear",
        price: 89.99,
        salePrice: 69.99,
        rating: 4.4,
        reviews: 345,
        stock: 280,
        sku: "FW-ESPAD-001",
        brand: "Soludos",
        images: ["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600"],
        description: "Classic espadrilles with jute sole and canvas upper.",
        variants: [
          { name: "Size", values: ["6", "7", "8", "9", "10", "11"] },
          { name: "Color", values: ["Navy", "White", "Red", "Natural"] },
        ],
      },

      // Watches & Jewelry - 6 products
      {
        name: "Luxury Automatic Watch",
        category: "watches-jewelry",
        price: 5999.99,
        salePrice: 4999.99,
        rating: 4.9,
        reviews: 89,
        stock: 15,
        sku: "WJ-WATCH-001",
        brand: "Omega",
        featured: true,
        images: ["https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600"],
        description: "Swiss-made automatic chronograph with sapphire crystal and 100m water resistance.",
        variants: [{ name: "Band", values: ["Stainless Steel", "Leather", "NATO Strap"] }],
      },
      {
        name: "Diamond Tennis Bracelet",
        category: "watches-jewelry",
        price: 2999.99,
        salePrice: 2499.99,
        rating: 4.9,
        reviews: 67,
        stock: 20,
        sku: "WJ-BRACE-001",
        brand: "Tiffany & Co.",
        images: ["https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600"],
        description: "18k white gold tennis bracelet with 3 carats of round brilliant diamonds.",
        variants: [{ name: "Size", values: ['6.5"', '7"', '7.5"'] }],
      },
      {
        name: "Pearl Necklace Set",
        category: "watches-jewelry",
        price: 1199.99,
        salePrice: 899.99,
        rating: 4.8,
        reviews: 123,
        stock: 40,
        sku: "WJ-PEARL-001",
        brand: "Mikimoto",
        images: ["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600"],
        description: "Cultured Akoya pearl necklace with 14k gold clasp, 7-7.5mm pearls.",
        variants: [{ name: "Length", values: ['16"', '18"', '20"'] }],
      },
      {
        name: "Gold Hoop Earrings",
        category: "watches-jewelry",
        price: 399.99,
        salePrice: 329.99,
        rating: 4.7,
        reviews: 234,
        stock: 100,
        sku: "WJ-HOOP-001",
        brand: "Mejuri",
        images: ["https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600"],
        description: "14k solid gold hoop earrings with click-top closure.",
        variants: [{ name: "Size", values: ["Small", "Medium", "Large"] }],
      },
      {
        name: "Minimalist Watch",
        category: "watches-jewelry",
        price: 295.0,
        salePrice: 249.0,
        rating: 4.6,
        reviews: 567,
        stock: 180,
        sku: "WJ-MINWATCH-001",
        brand: "Daniel Wellington",
        images: ["https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600"],
        description: "Classic minimalist watch with interchangeable straps.",
        variants: [{ name: "Strap", values: ["Black Leather", "Brown Leather", "Mesh Steel", "NATO"] }],
      },
      {
        name: "Sterling Silver Ring Set",
        category: "watches-jewelry",
        price: 149.99,
        salePrice: 119.99,
        rating: 4.5,
        reviews: 345,
        stock: 200,
        sku: "WJ-RING-001",
        brand: "Pandora",
        images: ["https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600"],
        description: "Set of 3 stackable sterling silver rings.",
        variants: [{ name: "Size", values: ["5", "6", "7", "8", "9"] }],
      },

      // Sportswear - 6 products
      {
        name: "Performance Running Set",
        category: "sportswear",
        price: 189.99,
        salePrice: 149.99,
        rating: 4.7,
        reviews: 567,
        stock: 300,
        sku: "SW-RUN-001",
        brand: "Nike",
        images: ["https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=600"],
        description: "Dri-FIT running top and shorts combo with reflective details.",
        variants: [
          { name: "Size", values: ["XS", "S", "M", "L", "XL", "XXL"] },
          { name: "Color", values: ["Black/Volt", "Navy/White", "Grey/Orange"] },
        ],
      },
      {
        name: "Yoga & Pilates Set",
        category: "sportswear",
        price: 159.99,
        salePrice: 129.99,
        rating: 4.8,
        reviews: 892,
        stock: 400,
        sku: "SW-YOGA-001",
        brand: "Lululemon",
        featured: true,
        images: ["https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600"],
        description: "High-rise leggings and sports bra set with four-way stretch.",
        variants: [
          { name: "Size", values: ["XS", "S", "M", "L", "XL"] },
          { name: "Color", values: ["Black", "Navy", "Burgundy", "Forest Green"] },
        ],
      },
      {
        name: "Training Shoes Pro",
        category: "sportswear",
        price: 199.99,
        salePrice: 159.99,
        rating: 4.6,
        reviews: 1456,
        stock: 500,
        sku: "SW-TRAIN-001",
        brand: "Under Armour",
        images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600"],
        description: "Versatile training shoes with responsive cushioning and stability.",
        variants: [
          { name: "Size", values: ["6", "7", "8", "9", "10", "11", "12", "13"] },
          { name: "Color", values: ["Black/White", "Grey/Volt", "Navy/Red"] },
        ],
      },
      {
        name: "Compression Leggings",
        category: "sportswear",
        price: 79.99,
        salePrice: 59.99,
        rating: 4.5,
        reviews: 678,
        stock: 350,
        sku: "SW-COMP-001",
        brand: "2XU",
        images: ["https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600"],
        description: "High-performance compression leggings for training and recovery.",
        variants: [
          { name: "Size", values: ["XS", "S", "M", "L", "XL"] },
          { name: "Color", values: ["Black", "Navy", "Grey"] },
        ],
      },
      {
        name: "Golf Polo Shirt",
        category: "sportswear",
        price: 89.99,
        salePrice: 69.99,
        rating: 4.6,
        reviews: 234,
        stock: 280,
        sku: "SW-GOLF-001",
        brand: "Puma",
        images: ["https://images.unsplash.com/photo-1625910513413-5fc45e80b77c?w=600"],
        description: "Moisture-wicking golf polo with UV protection.",
        variants: [
          { name: "Size", values: ["S", "M", "L", "XL", "XXL"] },
          { name: "Color", values: ["White", "Navy", "Black", "Red"] },
        ],
      },
      {
        name: "Swimming Goggles Pro",
        category: "sportswear",
        price: 49.99,
        salePrice: 39.99,
        rating: 4.7,
        reviews: 456,
        stock: 400,
        sku: "SW-SWIM-001",
        brand: "Speedo",
        images: ["https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=600"],
        description: "Anti-fog racing goggles with UV protection.",
        variants: [{ name: "Color", values: ["Clear", "Blue", "Smoke", "Mirrored"] }],
      },
    ],
  },
  {
    name: "TechHub Electronics",
    slug: "tech-hub",
    description: "Your ultimate destination for cutting-edge technology, gadgets, and electronics",
    industry: "electronics",
    owner: {
      email: "owner@techhub.com",
      password: "Owner@123456",
      firstName: "James",
      lastName: "Chen",
    },
    branding: {
      primaryColor: "#3b82f6",
      secondaryColor: "#1d4ed8",
      accentColor: "#10b981",
    },
    categories: [
      { name: "Smartphones", slug: "smartphones", image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400" },
      { name: "Laptops & Computers", slug: "laptops-computers", image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400" },
      { name: "Audio & Headphones", slug: "audio-headphones", image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400" },
      { name: "Gaming", slug: "gaming", image: "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=400" },
      { name: "Smart Home", slug: "smart-home", image: "https://images.unsplash.com/photo-1558089687-f282ffcbc126?w=400" },
      { name: "Cameras & Drones", slug: "cameras-drones", image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400" },
      { name: "Wearables", slug: "wearables", image: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=400" },
      { name: "Accessories", slug: "tech-accessories", image: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400" },
    ],
    products: [
      // Smartphones - 6 products
      {
        name: "iPhone 15 Pro Max",
        category: "smartphones",
        price: 1199.0,
        salePrice: null,
        rating: 4.9,
        reviews: 2345,
        stock: 150,
        sku: "SP-IPH15PM-001",
        brand: "Apple",
        featured: true,
        images: ["https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600", "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=600"],
        description: "The most powerful iPhone ever. A17 Pro chip, 48MP camera system, titanium design, and all-day battery life.",
        variants: [
          { name: "Storage", values: ["256GB", "512GB", "1TB"] },
          { name: "Color", values: ["Natural Titanium", "Blue Titanium", "White Titanium", "Black Titanium"] },
        ],
      },
      {
        name: "Samsung Galaxy S24 Ultra",
        category: "smartphones",
        price: 1299.99,
        salePrice: 1199.99,
        rating: 4.8,
        reviews: 1876,
        stock: 120,
        sku: "SP-SGS24U-001",
        brand: "Samsung",
        featured: true,
        images: ["https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600"],
        description: "Ultimate Galaxy experience with Galaxy AI, 200MP camera, S Pen, and titanium frame.",
        variants: [
          { name: "Storage", values: ["256GB", "512GB", "1TB"] },
          { name: "Color", values: ["Titanium Black", "Titanium Gray", "Titanium Violet", "Titanium Yellow"] },
        ],
      },
      {
        name: "Google Pixel 8 Pro",
        category: "smartphones",
        price: 999.0,
        salePrice: 899.0,
        rating: 4.7,
        reviews: 987,
        stock: 80,
        sku: "SP-GP8P-001",
        brand: "Google",
        images: ["https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600"],
        description: "The best of Google with advanced AI features, exceptional camera, and 7 years of updates.",
        variants: [
          { name: "Storage", values: ["128GB", "256GB", "512GB"] },
          { name: "Color", values: ["Obsidian", "Porcelain", "Bay"] },
        ],
      },
      {
        name: "OnePlus 12",
        category: "smartphones",
        price: 799.0,
        salePrice: 749.0,
        rating: 4.6,
        reviews: 567,
        stock: 100,
        sku: "SP-OP12-001",
        brand: "OnePlus",
        images: ["https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600"],
        description: "Flagship killer with Snapdragon 8 Gen 3 and 100W fast charging.",
        variants: [
          { name: "Storage", values: ["256GB", "512GB"] },
          { name: "Color", values: ["Silky Black", "Flowy Emerald"] },
        ],
      },
      {
        name: "iPhone 15",
        category: "smartphones",
        price: 799.0,
        salePrice: 749.0,
        rating: 4.7,
        reviews: 1567,
        stock: 200,
        sku: "SP-IPH15-001",
        brand: "Apple",
        images: ["https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=600"],
        description: "Dynamic Island, 48MP camera, and USB-C connectivity.",
        variants: [
          { name: "Storage", values: ["128GB", "256GB", "512GB"] },
          { name: "Color", values: ["Black", "Blue", "Green", "Yellow", "Pink"] },
        ],
      },
      {
        name: "Samsung Galaxy Z Fold 5",
        category: "smartphones",
        price: 1799.99,
        salePrice: 1599.99,
        rating: 4.6,
        reviews: 432,
        stock: 40,
        sku: "SP-SGZF5-001",
        brand: "Samsung",
        featured: true,
        images: ["https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600"],
        description: "Unfold your world with the ultimate foldable smartphone.",
        variants: [
          { name: "Storage", values: ["256GB", "512GB", "1TB"] },
          { name: "Color", values: ["Phantom Black", "Cream", "Icy Blue"] },
        ],
      },

      // Laptops & Computers - 8 products
      {
        name: 'MacBook Pro 16" M3 Max',
        category: "laptops-computers",
        price: 3499.0,
        salePrice: null,
        rating: 4.9,
        reviews: 567,
        stock: 40,
        sku: "LP-MBP16M3-001",
        brand: "Apple",
        featured: true,
        images: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600"],
        description: "Supercharged by M3 Max. Up to 128GB unified memory, 22-hour battery life, and stunning Liquid Retina XDR display.",
        variants: [
          { name: "Config", values: ["M3 Pro 36GB/512GB", "M3 Max 48GB/1TB", "M3 Max 128GB/4TB"] },
          { name: "Color", values: ["Space Black", "Silver"] },
        ],
      },
      {
        name: "Dell XPS 15 OLED",
        category: "laptops-computers",
        price: 2199.99,
        salePrice: 1899.99,
        rating: 4.7,
        reviews: 432,
        stock: 60,
        sku: "LP-DXPS15-001",
        brand: "Dell",
        images: ["https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600"],
        description: "Premium ultrabook with stunning 3.5K OLED display and Intel Core i9.",
        variants: [{ name: "Config", values: ["i7/16GB/512GB", "i9/32GB/1TB", "i9/64GB/2TB"] }],
      },
      {
        name: "Alienware Aurora R16",
        category: "laptops-computers",
        price: 3999.99,
        salePrice: 3499.99,
        rating: 4.9,
        reviews: 234,
        stock: 25,
        sku: "LP-GDESK-001",
        brand: "Alienware",
        featured: true,
        images: ["https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=600"],
        description: "Ultimate gaming rig with RTX 4090, Intel i9-14900K, and custom liquid cooling.",
        variants: [{ name: "GPU", values: ["RTX 4080", "RTX 4090"] }],
      },
      {
        name: "Microsoft Surface Pro 9",
        category: "laptops-computers",
        price: 1799.99,
        salePrice: 1599.99,
        rating: 4.6,
        reviews: 678,
        stock: 90,
        sku: "LP-MSSP9-001",
        brand: "Microsoft",
        images: ["https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=600"],
        description: "2-in-1 laptop and tablet with Intel Core i7 and Windows 11.",
        variants: [
          { name: "Config", values: ["i5/8GB/256GB", "i7/16GB/512GB", "i7/32GB/1TB"] },
          { name: "Color", values: ["Platinum", "Graphite", "Sapphire", "Forest"] },
        ],
      },
      {
        name: 'MacBook Air 15" M3',
        category: "laptops-computers",
        price: 1299.0,
        salePrice: 1199.0,
        rating: 4.8,
        reviews: 789,
        stock: 100,
        sku: "LP-MBA15M3-001",
        brand: "Apple",
        images: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600"],
        description: "Impossibly thin design with M3 chip and 18-hour battery life.",
        variants: [
          { name: "Config", values: ["8GB/256GB", "16GB/512GB", "24GB/1TB"] },
          { name: "Color", values: ["Midnight", "Starlight", "Space Gray", "Silver"] },
        ],
      },
      {
        name: "Lenovo ThinkPad X1 Carbon",
        category: "laptops-computers",
        price: 1849.99,
        salePrice: 1649.99,
        rating: 4.7,
        reviews: 345,
        stock: 70,
        sku: "LP-TPX1C-001",
        brand: "Lenovo",
        images: ["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600"],
        description: "Legendary business laptop with Intel Core Ultra and 2.8K OLED.",
        variants: [{ name: "Config", values: ["i5/16GB/512GB", "i7/32GB/1TB"] }],
      },
      {
        name: "ASUS ROG Strix G16",
        category: "laptops-computers",
        price: 1999.99,
        salePrice: 1799.99,
        rating: 4.6,
        reviews: 456,
        stock: 55,
        sku: "LP-ROGG16-001",
        brand: "ASUS",
        images: ["https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600"],
        description: "Gaming laptop with RTX 4070 and 240Hz display.",
        variants: [{ name: "Config", values: ["RTX 4060/16GB", "RTX 4070/32GB"] }],
      },
      {
        name: "Mac Mini M2 Pro",
        category: "laptops-computers",
        price: 1299.0,
        salePrice: 1199.0,
        rating: 4.8,
        reviews: 234,
        stock: 80,
        sku: "LP-MMINI-001",
        brand: "Apple",
        images: ["https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=600"],
        description: "Compact powerhouse with M2 Pro chip.",
        variants: [{ name: "Config", values: ["M2/16GB/512GB", "M2 Pro/32GB/1TB"] }],
      },

      // Audio & Headphones - 8 products
      {
        name: "Sony WH-1000XM5",
        category: "audio-headphones",
        price: 399.99,
        salePrice: 349.99,
        rating: 4.8,
        reviews: 3456,
        stock: 200,
        sku: "AH-SNYWH5-001",
        brand: "Sony",
        featured: true,
        images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600"],
        description: "Industry-leading noise cancellation with 30-hour battery life and exceptional comfort.",
        variants: [{ name: "Color", values: ["Black", "Silver", "Midnight Blue"] }],
      },
      {
        name: "AirPods Pro (2nd Gen)",
        category: "audio-headphones",
        price: 249.0,
        salePrice: null,
        rating: 4.7,
        reviews: 5678,
        stock: 300,
        sku: "AH-APP2-001",
        brand: "Apple",
        images: ["https://images.unsplash.com/photo-1588156979435-379b9d802b0a?w=600"],
        description: "Rebuilt from the ground up with H2 chip, adaptive audio, and USB-C charging.",
      },
      {
        name: "Bose QuietComfort Ultra",
        category: "audio-headphones",
        price: 449.99,
        salePrice: 399.99,
        rating: 4.8,
        reviews: 1234,
        stock: 150,
        sku: "AH-BQCU-001",
        brand: "Bose",
        images: ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600"],
        description: "World-class noise cancellation with spatial audio and immersive sound.",
        variants: [{ name: "Color", values: ["Black", "White Smoke", "Sandstone"] }],
      },
      {
        name: "Sonos Era 300",
        category: "audio-headphones",
        price: 449.0,
        salePrice: null,
        rating: 4.7,
        reviews: 567,
        stock: 80,
        sku: "AH-SNS300-001",
        brand: "Sonos",
        images: ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600"],
        description: "Premium spatial audio speaker with Dolby Atmos and voice control.",
        variants: [{ name: "Color", values: ["Black", "White"] }],
      },
      {
        name: "AirPods Max",
        category: "audio-headphones",
        price: 549.0,
        salePrice: 499.0,
        rating: 4.6,
        reviews: 2345,
        stock: 100,
        sku: "AH-APM-001",
        brand: "Apple",
        featured: true,
        images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600"],
        description: "High-fidelity audio with Active Noise Cancellation and spatial audio.",
        variants: [{ name: "Color", values: ["Silver", "Space Gray", "Green", "Pink", "Sky Blue"] }],
      },
      {
        name: "Samsung Galaxy Buds2 Pro",
        category: "audio-headphones",
        price: 229.99,
        salePrice: 179.99,
        rating: 4.5,
        reviews: 1234,
        stock: 250,
        sku: "AH-SGB2P-001",
        brand: "Samsung",
        images: ["https://images.unsplash.com/photo-1588156979435-379b9d802b0a?w=600"],
        description: "Hi-Fi sound with intelligent ANC and 360 Audio.",
        variants: [{ name: "Color", values: ["Graphite", "White", "Bora Purple"] }],
      },
      {
        name: "Sennheiser Momentum 4",
        category: "audio-headphones",
        price: 379.99,
        salePrice: 329.99,
        rating: 4.7,
        reviews: 678,
        stock: 120,
        sku: "AH-SM4-001",
        brand: "Sennheiser",
        images: ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600"],
        description: "Audiophile-grade wireless headphones with 60-hour battery.",
        variants: [{ name: "Color", values: ["Black", "White", "Graphite"] }],
      },
      {
        name: "JBL Flip 6",
        category: "audio-headphones",
        price: 129.99,
        salePrice: 99.99,
        rating: 4.6,
        reviews: 3456,
        stock: 400,
        sku: "AH-JBLF6-001",
        brand: "JBL",
        images: ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600"],
        description: "Portable Bluetooth speaker with powerful sound and IP67 rating.",
        variants: [{ name: "Color", values: ["Black", "Blue", "Red", "Teal", "Pink"] }],
      },

      // Gaming - 8 products
      {
        name: "PlayStation 5 Pro",
        category: "gaming",
        price: 699.99,
        salePrice: null,
        rating: 4.9,
        reviews: 2345,
        stock: 50,
        sku: "GM-PS5PRO-001",
        brand: "Sony",
        featured: true,
        images: ["https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=600"],
        description: "The most powerful PlayStation ever. Enhanced 4K gaming, ray tracing, and ultra-fast SSD.",
      },
      {
        name: "Xbox Series X",
        category: "gaming",
        price: 499.99,
        salePrice: null,
        rating: 4.8,
        reviews: 1987,
        stock: 75,
        sku: "GM-XBSX-001",
        brand: "Microsoft",
        images: ["https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=600"],
        description: "12 teraflops of raw graphic processing power, true 4K gaming, and Quick Resume.",
      },
      {
        name: "Nintendo Switch OLED",
        category: "gaming",
        price: 349.99,
        salePrice: null,
        rating: 4.7,
        reviews: 4567,
        stock: 200,
        sku: "GM-NSWOLED-001",
        brand: "Nintendo",
        images: ["https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=600"],
        description: "Vivid 7-inch OLED screen, enhanced audio, and 64GB internal storage.",
        variants: [{ name: "Color", values: ["White", "Neon Red/Blue"] }],
      },
      {
        name: "Razer BlackWidow V4 Pro",
        category: "gaming",
        price: 279.99,
        salePrice: 229.99,
        rating: 4.6,
        reviews: 876,
        stock: 150,
        sku: "GM-RZBWV4-001",
        brand: "Razer",
        images: ["https://images.unsplash.com/photo-1595225476474-87563907a212?w=600"],
        description: "Mechanical gaming keyboard with optical switches and Razer Chroma RGB.",
        variants: [{ name: "Switch", values: ["Green (Clicky)", "Yellow (Linear)", "Orange (Tactile)"] }],
      },
      {
        name: "Logitech G Pro X Superlight",
        category: "gaming",
        price: 159.99,
        salePrice: 139.99,
        rating: 4.8,
        reviews: 2345,
        stock: 300,
        sku: "GM-LGPXS-001",
        brand: "Logitech",
        featured: true,
        images: ["https://images.unsplash.com/photo-1595225476474-87563907a212?w=600"],
        description: "Ultra-lightweight wireless gaming mouse with HERO 25K sensor.",
        variants: [{ name: "Color", values: ["Black", "White", "Pink"] }],
      },
      {
        name: "SteelSeries Arctis Nova Pro",
        category: "gaming",
        price: 349.99,
        salePrice: 299.99,
        rating: 4.7,
        reviews: 567,
        stock: 100,
        sku: "GM-SSANP-001",
        brand: "SteelSeries",
        images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600"],
        description: "Premium wireless gaming headset with Active Noise Cancellation.",
        variants: [{ name: "Platform", values: ["PC/PlayStation", "Xbox"] }],
      },
      {
        name: "ASUS ROG Swift OLED PG27AQDM",
        category: "gaming",
        price: 999.99,
        salePrice: 899.99,
        rating: 4.9,
        reviews: 234,
        stock: 40,
        sku: "GM-ROGM27-001",
        brand: "ASUS",
        images: ["https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=600"],
        description: '27" OLED gaming monitor with 240Hz refresh rate and 0.03ms response time.',
      },
      {
        name: "Elgato Stream Deck +",
        category: "gaming",
        price: 199.99,
        salePrice: 179.99,
        rating: 4.6,
        reviews: 456,
        stock: 180,
        sku: "GM-ELSD-001",
        brand: "Elgato",
        images: ["https://images.unsplash.com/photo-1595225476474-87563907a212?w=600"],
        description: "Studio controller with customizable LCD keys and touch strip.",
      },

      // Smart Home - 6 products
      {
        name: "Google Nest Hub Max",
        category: "smart-home",
        price: 249.99,
        salePrice: 229.99,
        rating: 4.6,
        reviews: 2345,
        stock: 180,
        sku: "SH-GNHM-001",
        brand: "Google",
        images: ["https://images.unsplash.com/photo-1558089687-f282ffcbc126?w=600"],
        description: "10-inch smart display with Nest Cam, Google Assistant, and video calling.",
        variants: [{ name: "Color", values: ["Chalk", "Charcoal"] }],
      },
      {
        name: "Ring Video Doorbell Pro 2",
        category: "smart-home",
        price: 279.99,
        salePrice: 249.99,
        rating: 4.7,
        reviews: 3456,
        stock: 250,
        sku: "SH-RVDBP2-001",
        brand: "Ring",
        featured: true,
        images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600"],
        description: "Advanced video doorbell with 3D Motion Detection and Bird's Eye View.",
      },
      {
        name: "Philips Hue Starter Kit",
        category: "smart-home",
        price: 249.99,
        salePrice: 199.99,
        rating: 4.8,
        reviews: 4567,
        stock: 300,
        sku: "SH-PHSK-001",
        brand: "Philips",
        images: ["https://images.unsplash.com/photo-1545259741-2266da59fa8c?w=600"],
        description: "4 smart bulbs and bridge for whole-home lighting control with 16 million colors.",
      },
      {
        name: "Ecobee Smart Thermostat",
        category: "smart-home",
        price: 299.99,
        salePrice: 249.99,
        rating: 4.7,
        reviews: 1234,
        stock: 120,
        sku: "SH-ECST-001",
        brand: "Ecobee",
        images: ["https://images.unsplash.com/photo-1567925086983-a5a5e8b86a98?w=600"],
        description: "Premium smart thermostat with voice control and SmartSensor included.",
      },
      {
        name: "Amazon Echo Show 10",
        category: "smart-home",
        price: 249.99,
        salePrice: 219.99,
        rating: 4.5,
        reviews: 2345,
        stock: 200,
        sku: "SH-AESH10-001",
        brand: "Amazon",
        images: ["https://images.unsplash.com/photo-1558089687-f282ffcbc126?w=600"],
        description: "HD smart display that moves with you, with Alexa and 13MP camera.",
        variants: [{ name: "Color", values: ["Charcoal", "Glacier White"] }],
      },
      {
        name: "Arlo Pro 5S 2K",
        category: "smart-home",
        price: 249.99,
        salePrice: 199.99,
        rating: 4.6,
        reviews: 1567,
        stock: 220,
        sku: "SH-ARP5S-001",
        brand: "Arlo",
        images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600"],
        description: "Wireless security camera with 2K video, color night vision, and 12x zoom.",
      },

      // Cameras & Drones - 6 products
      {
        name: "Sony Alpha A7 IV",
        category: "cameras-drones",
        price: 2698.0,
        salePrice: 2498.0,
        rating: 4.9,
        reviews: 567,
        stock: 35,
        sku: "CD-SA7IV-001",
        brand: "Sony",
        featured: true,
        images: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600"],
        description: "Full-frame mirrorless camera with 33MP sensor and advanced autofocus.",
      },
      {
        name: "DJI Mavic 3 Pro",
        category: "cameras-drones",
        price: 2399.0,
        salePrice: 2199.0,
        rating: 4.8,
        reviews: 432,
        stock: 45,
        sku: "CD-DJM3P-001",
        brand: "DJI",
        featured: true,
        images: ["https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600"],
        description: "Flagship drone with triple-camera system and 43-min flight time.",
      },
      {
        name: "GoPro HERO12 Black",
        category: "cameras-drones",
        price: 449.99,
        salePrice: 399.99,
        rating: 4.7,
        reviews: 2345,
        stock: 200,
        sku: "CD-GPH12-001",
        brand: "GoPro",
        images: ["https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600"],
        description: "Ultimate action camera with HyperSmooth 6.0 and 5.3K video.",
      },
      {
        name: "Canon EOS R6 Mark II",
        category: "cameras-drones",
        price: 2499.0,
        salePrice: 2299.0,
        rating: 4.8,
        reviews: 345,
        stock: 40,
        sku: "CD-CR6M2-001",
        brand: "Canon",
        images: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600"],
        description: "Full-frame mirrorless with 24.2MP and up to 40fps continuous shooting.",
      },
      {
        name: "DJI Mini 4 Pro",
        category: "cameras-drones",
        price: 1099.0,
        salePrice: 999.0,
        rating: 4.7,
        reviews: 678,
        stock: 80,
        sku: "CD-DJMINI4-001",
        brand: "DJI",
        images: ["https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600"],
        description: "Sub-249g drone with 4K/60fps video and omnidirectional obstacle sensing.",
      },
      {
        name: "Insta360 X4",
        category: "cameras-drones",
        price: 499.99,
        salePrice: 449.99,
        rating: 4.6,
        reviews: 456,
        stock: 120,
        sku: "CD-I360X4-001",
        brand: "Insta360",
        images: ["https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600"],
        description: "8K 360-degree camera with AI editing and waterproof design.",
      },

      // Wearables - 6 products
      {
        name: "Apple Watch Ultra 2",
        category: "wearables",
        price: 799.0,
        salePrice: null,
        rating: 4.9,
        reviews: 1234,
        stock: 80,
        sku: "WB-AWU2-001",
        brand: "Apple",
        featured: true,
        images: ["https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600"],
        description: "The most rugged and capable Apple Watch. 49mm titanium case, precision dual-frequency GPS.",
        variants: [{ name: "Band", values: ["Alpine Loop", "Trail Loop", "Ocean Band"] }],
      },
      {
        name: "Samsung Galaxy Watch 6 Classic",
        category: "wearables",
        price: 449.99,
        salePrice: 399.99,
        rating: 4.7,
        reviews: 876,
        stock: 120,
        sku: "WB-SGW6C-001",
        brand: "Samsung",
        images: ["https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600"],
        description: "Premium smartwatch with rotating bezel, advanced health monitoring, and Wear OS.",
        variants: [
          { name: "Size", values: ["43mm", "47mm"] },
          { name: "Color", values: ["Black", "Silver"] },
        ],
      },
      {
        name: "Oura Ring Gen 3",
        category: "wearables",
        price: 349.0,
        salePrice: 299.0,
        rating: 4.6,
        reviews: 2345,
        stock: 200,
        sku: "WB-ORG3-001",
        brand: "Oura",
        images: ["https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600"],
        description: "Smart ring with advanced sleep tracking and health insights.",
        variants: [
          { name: "Size", values: ["6", "7", "8", "9", "10", "11", "12", "13"] },
          { name: "Finish", values: ["Silver", "Black", "Gold", "Rose Gold"] },
        ],
      },
      {
        name: "Garmin Fenix 8",
        category: "wearables",
        price: 899.99,
        salePrice: 799.99,
        rating: 4.8,
        reviews: 567,
        stock: 60,
        sku: "WB-GF8-001",
        brand: "Garmin",
        featured: true,
        images: ["https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600"],
        description: "Premium multisport GPS watch with AMOLED display and advanced training metrics.",
        variants: [{ name: "Size", values: ["47mm", "51mm"] }],
      },
      {
        name: "Fitbit Sense 2",
        category: "wearables",
        price: 299.99,
        salePrice: 249.99,
        rating: 4.5,
        reviews: 1234,
        stock: 180,
        sku: "WB-FBS2-001",
        brand: "Fitbit",
        images: ["https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600"],
        description: "Advanced health smartwatch with stress management and ECG app.",
        variants: [{ name: "Color", values: ["Graphite", "Lunar White", "Blue Mist"] }],
      },
      {
        name: "Whoop 4.0",
        category: "wearables",
        price: 239.0,
        salePrice: null,
        rating: 4.6,
        reviews: 789,
        stock: 150,
        sku: "WB-WH4-001",
        brand: "Whoop",
        images: ["https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600"],
        description: "Continuous health monitoring wearable with strain, recovery, and sleep tracking.",
      },

      // Tech Accessories - 8 products
      {
        name: "Anker 737 Power Bank",
        category: "tech-accessories",
        price: 179.99,
        salePrice: 149.99,
        rating: 4.8,
        reviews: 3456,
        stock: 300,
        sku: "TA-A737PB-001",
        brand: "Anker",
        images: ["https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600"],
        description: "24,000mAh power bank with 140W output and smart digital display.",
      },
      {
        name: "Belkin MagSafe 3-in-1",
        category: "tech-accessories",
        price: 169.99,
        salePrice: 149.99,
        rating: 4.7,
        reviews: 1234,
        stock: 200,
        sku: "TA-BMS31-001",
        brand: "Belkin",
        images: ["https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600"],
        description: "Wireless charger for iPhone, Apple Watch, and AirPods with fast charging.",
      },
      {
        name: "CalDigit TS4 Thunderbolt 4",
        category: "tech-accessories",
        price: 449.99,
        salePrice: 399.99,
        rating: 4.9,
        reviews: 567,
        stock: 80,
        sku: "TA-CDTS4-001",
        brand: "CalDigit",
        images: ["https://images.unsplash.com/photo-1625842268584-8f3296236761?w=600"],
        description: "18-port Thunderbolt 4 dock with 98W laptop charging.",
      },
      {
        name: "Samsung T7 Shield SSD",
        category: "tech-accessories",
        price: 179.99,
        salePrice: 149.99,
        rating: 4.7,
        reviews: 2345,
        stock: 250,
        sku: "TA-ST7S-001",
        brand: "Samsung",
        images: ["https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600"],
        description: "2TB portable SSD with IP65 rating and 1,050MB/s speeds.",
        variants: [{ name: "Capacity", values: ["1TB", "2TB", "4TB"] }],
      },
      {
        name: "Logitech MX Master 3S",
        category: "tech-accessories",
        price: 99.99,
        salePrice: 89.99,
        rating: 4.8,
        reviews: 4567,
        stock: 400,
        sku: "TA-MXM3S-001",
        brand: "Logitech",
        featured: true,
        images: ["https://images.unsplash.com/photo-1625842268584-8f3296236761?w=600"],
        description: "Advanced wireless mouse with quiet clicks and 8K DPI tracking.",
        variants: [{ name: "Color", values: ["Graphite", "Pale Gray"] }],
      },
      {
        name: "Apple Magic Keyboard",
        category: "tech-accessories",
        price: 199.0,
        salePrice: null,
        rating: 4.6,
        reviews: 1234,
        stock: 180,
        sku: "TA-AMK-001",
        brand: "Apple",
        images: ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600"],
        description: "Wireless keyboard with Touch ID and numeric keypad.",
        variants: [{ name: "Color", values: ["White/Silver", "Black/Space Gray"] }],
      },
      {
        name: "Nomad Base One Max",
        category: "tech-accessories",
        price: 179.99,
        salePrice: 159.99,
        rating: 4.5,
        reviews: 678,
        stock: 150,
        sku: "TA-NBM-001",
        brand: "Nomad",
        images: ["https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600"],
        description: "MagSafe compatible wireless charger with Apple Watch mount.",
      },
      {
        name: "Peak Design Travel Tripod",
        category: "tech-accessories",
        price: 599.99,
        salePrice: 549.99,
        rating: 4.8,
        reviews: 345,
        stock: 60,
        sku: "TA-PDTT-001",
        brand: "Peak Design",
        images: ["https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600"],
        description: "Ultra-compact full-size tripod in carbon fiber.",
      },
    ],
  },
  {
    name: "GlowBeauty Cosmetics",
    slug: "glow-beauty",
    description: "Premium beauty, skincare, and cosmetics for the modern individual",
    industry: "cosmetics",
    owner: {
      email: "owner@glowbeauty.com",
      password: "Owner@123456",
      firstName: "Emily",
      lastName: "Rodriguez",
    },
    branding: {
      primaryColor: "#ec4899",
      secondaryColor: "#db2777",
      accentColor: "#f59e0b",
    },
    categories: [
      { name: "Skincare", slug: "skincare", image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400" },
      { name: "Makeup", slug: "makeup", image: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=400" },
      { name: "Fragrances", slug: "fragrances", image: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=400" },
      { name: "Hair Care", slug: "hair-care", image: "https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=400" },
      { name: "Body Care", slug: "body-care", image: "https://images.unsplash.com/photo-1570194065650-d99fb4b38b17?w=400" },
      { name: "Tools & Accessories", slug: "tools-accessories", image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400" },
    ],
    products: [
      // Skincare - 12 products
      {
        name: "La Mer Crème de la Mer",
        category: "skincare",
        price: 380.0,
        salePrice: null,
        rating: 4.9,
        reviews: 2345,
        stock: 60,
        sku: "SK-LMCM-001",
        brand: "La Mer",
        featured: true,
        images: ["https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600"],
        description: "The iconic Miracle Broth-infused moisturizer for unparalleled radiance and hydration.",
        variants: [{ name: "Size", values: ["0.5 oz", "1 oz", "2 oz", "3.4 oz"] }],
      },
      {
        name: "SK-II Facial Treatment Essence",
        category: "skincare",
        price: 210.0,
        salePrice: 185.0,
        rating: 4.8,
        reviews: 4567,
        stock: 100,
        sku: "SK-SKIIFTE-001",
        brand: "SK-II",
        featured: true,
        images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600"],
        description: "The legendary essence with over 90% PITERA for crystal clear skin.",
        variants: [{ name: "Size", values: ["2.5 oz", "5.4 oz", "7.7 oz"] }],
      },
      {
        name: "Drunk Elephant Protini",
        category: "skincare",
        price: 78.0,
        salePrice: 68.0,
        rating: 4.7,
        reviews: 3456,
        stock: 150,
        sku: "SK-DEPP-001",
        brand: "Drunk Elephant",
        images: ["https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?w=600"],
        description: "Protein moisturizer packed with signal peptides and growth factors.",
        variants: [{ name: "Size", values: ["0.5 oz", "1.69 oz"] }],
      },
      {
        name: "Tatcha Dewy Skin Cream",
        category: "skincare",
        price: 79.0,
        salePrice: 69.0,
        rating: 4.8,
        reviews: 2345,
        stock: 120,
        sku: "SK-TDSC-001",
        brand: "Tatcha",
        featured: true,
        images: ["https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600"],
        description: "Rich cream that feeds skin with plumping hydration and a dewy glow.",
      },
      {
        name: "The Ordinary Niacinamide 10%",
        category: "skincare",
        price: 12.9,
        salePrice: null,
        rating: 4.6,
        reviews: 8765,
        stock: 500,
        sku: "SK-TONIA-001",
        brand: "The Ordinary",
        images: ["https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600"],
        description: "High-strength vitamin and mineral blemish formula for visible pores and uneven tone.",
      },
      {
        name: "Sunday Riley Good Genes",
        category: "skincare",
        price: 142.0,
        salePrice: 122.0,
        rating: 4.7,
        reviews: 1234,
        stock: 80,
        sku: "SK-SRGG-001",
        brand: "Sunday Riley",
        images: ["https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600"],
        description: "All-in-one lactic acid treatment for instant clarity and radiance.",
        variants: [{ name: "Size", values: ["0.5 oz", "1 oz", "1.7 oz"] }],
      },
      {
        name: "Paula's Choice 2% BHA",
        category: "skincare",
        price: 34.0,
        salePrice: 29.0,
        rating: 4.8,
        reviews: 5678,
        stock: 300,
        sku: "SK-PC2BHA-001",
        brand: "Paula's Choice",
        images: ["https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600"],
        description: "Leave-on exfoliant for unclogging pores and smoothing wrinkles.",
      },
      {
        name: "CeraVe Hydrating Cleanser",
        category: "skincare",
        price: 18.99,
        salePrice: 14.99,
        rating: 4.7,
        reviews: 9876,
        stock: 600,
        sku: "SK-CVHC-001",
        brand: "CeraVe",
        images: ["https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600"],
        description: "Gentle, non-foaming cleanser with ceramides and hyaluronic acid.",
        variants: [{ name: "Size", values: ["8 oz", "12 oz", "16 oz"] }],
      },
      {
        name: "Estée Lauder Advanced Night Repair",
        category: "skincare",
        price: 110.0,
        salePrice: 95.0,
        rating: 4.8,
        reviews: 3456,
        stock: 150,
        sku: "SK-ELANR-001",
        brand: "Estée Lauder",
        featured: true,
        images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600"],
        description: "Iconic serum that reduces the look of lines and wrinkles.",
        variants: [{ name: "Size", values: ["1 oz", "1.7 oz", "3.4 oz"] }],
      },
      {
        name: "Kiehl's Ultra Facial Cream",
        category: "skincare",
        price: 38.0,
        salePrice: 32.0,
        rating: 4.6,
        reviews: 4567,
        stock: 250,
        sku: "SK-KUFC-001",
        brand: "Kiehl's",
        images: ["https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600"],
        description: "Lightweight 24-hour daily face moisturizer.",
        variants: [{ name: "Size", values: ["1.7 oz", "4.2 oz"] }],
      },
      {
        name: "Glow Recipe Watermelon Mask",
        category: "skincare",
        price: 45.0,
        salePrice: 38.0,
        rating: 4.5,
        reviews: 2345,
        stock: 180,
        sku: "SK-GRWM-001",
        brand: "Glow Recipe",
        images: ["https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600"],
        description: "Radiance-boosting sleeping mask with AHAs and hyaluronic acid.",
      },
      {
        name: "Clinique Moisture Surge",
        category: "skincare",
        price: 52.0,
        salePrice: 44.0,
        rating: 4.7,
        reviews: 3456,
        stock: 200,
        sku: "SK-CLMS-001",
        brand: "Clinique",
        images: ["https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?w=600"],
        description: "72-hour auto-replenishing hydrator for all skin types.",
        variants: [{ name: "Size", values: ["1 oz", "1.7 oz", "2.5 oz"] }],
      },

      // Makeup - 12 products
      {
        name: "Charlotte Tilbury Pillow Talk Set",
        category: "makeup",
        price: 168.0,
        salePrice: 148.0,
        rating: 4.9,
        reviews: 3456,
        stock: 100,
        sku: "MK-CTPTS-001",
        brand: "Charlotte Tilbury",
        featured: true,
        images: ["https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=600"],
        description: "Iconic Pillow Talk lip and cheek set in the universally flattering nude pink shade.",
      },
      {
        name: "NARS Radiant Creamy Concealer",
        category: "makeup",
        price: 32.0,
        salePrice: null,
        rating: 4.8,
        reviews: 6789,
        stock: 200,
        sku: "MK-NRCC-001",
        brand: "NARS",
        images: ["https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?w=600"],
        description: "Award-winning concealer that corrects, contours, and highlights.",
        variants: [{ name: "Shade", values: ["Chantilly", "Vanilla", "Custard", "Ginger", "Caramel", "Cacao"] }],
      },
      {
        name: "MAC Studio Fix Foundation",
        category: "makeup",
        price: 42.0,
        salePrice: 36.0,
        rating: 4.6,
        reviews: 5678,
        stock: 300,
        sku: "MK-MSFF-001",
        brand: "MAC",
        images: ["https://images.unsplash.com/photo-1631214526990-89e8fa3bd9c8?w=600"],
        description: "Buildable medium-to-full coverage foundation with 24-hour wear.",
        variants: [{ name: "Shade", values: ["NC15", "NC25", "NC35", "NC42", "NC50", "NW25", "NW35", "NW45"] }],
      },
      {
        name: "Urban Decay Naked Palette",
        category: "makeup",
        price: 65.0,
        salePrice: 55.0,
        rating: 4.7,
        reviews: 4567,
        stock: 180,
        sku: "MK-UDNP-001",
        brand: "Urban Decay",
        featured: true,
        images: ["https://images.unsplash.com/photo-1617220379175-68eb89278d82?w=600"],
        description: "12 stunning neutral eyeshadows from subtle shimmer to bold matte.",
      },
      {
        name: "Fenty Beauty Gloss Bomb",
        category: "makeup",
        price: 24.0,
        salePrice: 21.0,
        rating: 4.8,
        reviews: 7890,
        stock: 400,
        sku: "MK-FBGB-001",
        brand: "Fenty Beauty",
        images: ["https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600"],
        description: "Universal lip luminizer in the iconic shade that flatters all skin tones.",
        variants: [{ name: "Shade", values: ["Fenty Glow", "Hot Chocolit", "Fu$$y", "Diamond Milk", "Cheeky"] }],
      },
      {
        name: "Too Faced Better Than Sex Mascara",
        category: "makeup",
        price: 32.0,
        salePrice: 28.0,
        rating: 4.7,
        reviews: 9876,
        stock: 350,
        sku: "MK-TFBTS-001",
        brand: "Too Faced",
        images: ["https://images.unsplash.com/photo-1631214540553-ff044a3ff1ea?w=600"],
        description: "The #1 prestige mascara for volume, length, and curl.",
      },
      {
        name: "Rare Beauty Soft Pinch Blush",
        category: "makeup",
        price: 23.0,
        salePrice: 20.0,
        rating: 4.8,
        reviews: 4567,
        stock: 250,
        sku: "MK-RBSPB-001",
        brand: "Rare Beauty",
        featured: true,
        images: ["https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600"],
        description: "Weightless liquid blush that blends seamlessly.",
        variants: [{ name: "Shade", values: ["Joy", "Happy", "Bliss", "Grace", "Hope", "Love"] }],
      },
      {
        name: "Anastasia Brow Wiz",
        category: "makeup",
        price: 25.0,
        salePrice: 21.0,
        rating: 4.6,
        reviews: 5678,
        stock: 300,
        sku: "MK-ABBW-001",
        brand: "Anastasia Beverly Hills",
        images: ["https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?w=600"],
        description: "Ultra-slim mechanical brow pencil for precise definition.",
        variants: [{ name: "Shade", values: ["Blonde", "Taupe", "Soft Brown", "Medium Brown", "Dark Brown", "Ebony"] }],
      },
      {
        name: "Hourglass Veil Setting Powder",
        category: "makeup",
        price: 48.0,
        salePrice: 42.0,
        rating: 4.7,
        reviews: 2345,
        stock: 150,
        sku: "MK-HVSP-001",
        brand: "Hourglass",
        images: ["https://images.unsplash.com/photo-1631214526990-89e8fa3bd9c8?w=600"],
        description: "Talc-free finishing powder for a soft-focus finish.",
      },
      {
        name: "Pat McGrath MatteTrance Lipstick",
        category: "makeup",
        price: 39.0,
        salePrice: 34.0,
        rating: 4.8,
        reviews: 1234,
        stock: 120,
        sku: "MK-PMML-001",
        brand: "Pat McGrath Labs",
        images: ["https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600"],
        description: "Luxury matte lipstick with intense pigment.",
        variants: [{ name: "Shade", values: ["Elson", "Flesh 3", "Omi", "Full Panic", "Obsessed!"] }],
      },
      {
        name: "NYX Lip Liner",
        category: "makeup",
        price: 5.0,
        salePrice: 4.0,
        rating: 4.5,
        reviews: 8765,
        stock: 600,
        sku: "MK-NYXLL-001",
        brand: "NYX",
        images: ["https://images.unsplash.com/photo-1631214540553-ff044a3ff1ea?w=600"],
        description: "Creamy long-lasting lip liner in 30+ shades.",
        variants: [{ name: "Shade", values: ["Nude", "Natural", "Mauve", "Burgundy", "Deep Red", "Brown"] }],
      },
      {
        name: "Makeup Forever HD Foundation",
        category: "makeup",
        price: 43.0,
        salePrice: 38.0,
        rating: 4.6,
        reviews: 3456,
        stock: 200,
        sku: "MK-MUFHD-001",
        brand: "Makeup Forever",
        images: ["https://images.unsplash.com/photo-1631214526990-89e8fa3bd9c8?w=600"],
        description: "Professional-quality liquid foundation with natural finish.",
        variants: [{ name: "Shade", values: ["Y215", "Y225", "Y315", "Y405", "Y505", "R230", "R330", "R430"] }],
      },

      // Fragrances - 8 products
      {
        name: "Chanel No. 5 Eau de Parfum",
        category: "fragrances",
        price: 165.0,
        salePrice: 150.0,
        rating: 4.9,
        reviews: 2345,
        stock: 80,
        sku: "FR-CN5-001",
        brand: "Chanel",
        featured: true,
        images: ["https://images.unsplash.com/photo-1541643600914-78b084683601?w=600"],
        description: "The timeless classic fragrance with notes of ylang-ylang, rose, and sandalwood.",
        variants: [{ name: "Size", values: ["1.7 oz", "3.4 oz", "6.8 oz"] }],
      },
      {
        name: "Dior Sauvage EDT",
        category: "fragrances",
        price: 130.0,
        salePrice: 115.0,
        rating: 4.8,
        reviews: 4567,
        stock: 120,
        sku: "FR-DSED-001",
        brand: "Dior",
        featured: true,
        images: ["https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600"],
        description: "Raw, noble composition with fresh Calabrian bergamot and ambroxan.",
        variants: [{ name: "Size", values: ["2 oz", "3.4 oz", "6.8 oz"] }],
      },
      {
        name: "Tom Ford Black Orchid",
        category: "fragrances",
        price: 200.0,
        salePrice: 180.0,
        rating: 4.8,
        reviews: 1234,
        stock: 60,
        sku: "FR-TFBO-001",
        brand: "Tom Ford",
        images: ["https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=600"],
        description: "Luxurious and sensual fragrance with black truffle and ylang-ylang.",
        variants: [{ name: "Size", values: ["1 oz", "1.7 oz", "3.4 oz"] }],
      },
      {
        name: "Jo Malone Wood Sage & Sea Salt",
        category: "fragrances",
        price: 88.0,
        salePrice: 77.0,
        rating: 4.7,
        reviews: 2345,
        stock: 150,
        sku: "FR-JMWSS-001",
        brand: "Jo Malone",
        images: ["https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=600"],
        description: "Escape to wind-swept shores with this fresh, addictive cologne.",
        variants: [{ name: "Size", values: ["1 oz", "3.4 oz"] }],
      },
      {
        name: "Yves Saint Laurent Libre",
        category: "fragrances",
        price: 140.0,
        salePrice: 125.0,
        rating: 4.7,
        reviews: 1876,
        stock: 100,
        sku: "FR-YSLL-001",
        brand: "YSL",
        images: ["https://images.unsplash.com/photo-1541643600914-78b084683601?w=600"],
        description: "The scent of freedom with lavender essence and orange blossom.",
        variants: [{ name: "Size", values: ["1 oz", "1.7 oz", "3 oz"] }],
      },
      {
        name: "Marc Jacobs Daisy",
        category: "fragrances",
        price: 98.0,
        salePrice: 85.0,
        rating: 4.6,
        reviews: 3456,
        stock: 180,
        sku: "FR-MJD-001",
        brand: "Marc Jacobs",
        images: ["https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=600"],
        description: "Fresh and feminine with wild strawberry and soft musk.",
        variants: [{ name: "Size", values: ["1.7 oz", "3.4 oz"] }],
      },
      {
        name: "Versace Eros",
        category: "fragrances",
        price: 95.0,
        salePrice: 82.0,
        rating: 4.7,
        reviews: 2345,
        stock: 140,
        sku: "FR-VE-001",
        brand: "Versace",
        images: ["https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600"],
        description: "Bold masculine fragrance with mint and vanilla.",
        variants: [{ name: "Size", values: ["1.7 oz", "3.4 oz", "6.7 oz"] }],
      },
      {
        name: "Glossier You",
        category: "fragrances",
        price: 60.0,
        salePrice: 55.0,
        rating: 4.5,
        reviews: 1234,
        stock: 200,
        sku: "FR-GY-001",
        brand: "Glossier",
        images: ["https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=600"],
        description: "Personal fragrance that adapts to your skin.",
      },

      // Hair Care - 8 products
      {
        name: "Olaplex No.3 Hair Perfector",
        category: "hair-care",
        price: 35.0,
        salePrice: 30.0,
        rating: 4.8,
        reviews: 6789,
        stock: 300,
        sku: "HC-OLP3-001",
        brand: "Olaplex",
        featured: true,
        images: ["https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=600"],
        description: "At-home treatment that reduces breakage and strengthens hair.",
      },
      {
        name: "Dyson Airwrap Complete",
        category: "hair-care",
        price: 649.99,
        salePrice: 599.99,
        rating: 4.9,
        reviews: 3456,
        stock: 40,
        sku: "HC-DAWC-001",
        brand: "Dyson",
        featured: true,
        images: ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600"],
        description: "Style hair using air, not extreme heat. Includes all attachments for every hair type.",
      },
      {
        name: "Moroccanoil Treatment Original",
        category: "hair-care",
        price: 55.0,
        salePrice: 48.0,
        rating: 4.7,
        reviews: 4567,
        stock: 200,
        sku: "HC-MOT-001",
        brand: "Moroccanoil",
        images: ["https://images.unsplash.com/photo-1599305090598-fe179d501227?w=600"],
        description: "The original argan oil-infused treatment for all hair types.",
        variants: [{ name: "Size", values: ["0.85 oz", "1.7 oz", "3.4 oz"] }],
      },
      {
        name: "Kérastase Elixir Ultime Oil",
        category: "hair-care",
        price: 65.0,
        salePrice: 56.0,
        rating: 4.8,
        reviews: 2345,
        stock: 180,
        sku: "HC-KEU-001",
        brand: "Kérastase",
        images: ["https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600"],
        description: "Luxurious beautifying oil serum for brilliant shine and nutrition.",
      },
      {
        name: "Bumble and Bumble Thickening Spray",
        category: "hair-care",
        price: 32.0,
        salePrice: 28.0,
        rating: 4.5,
        reviews: 1876,
        stock: 250,
        sku: "HC-BBTS-001",
        brand: "Bumble and Bumble",
        images: ["https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=600"],
        description: "Lightweight spray for volume and fullness.",
      },
      {
        name: "Briogeo Don't Despair Repair Mask",
        category: "hair-care",
        price: 42.0,
        salePrice: 36.0,
        rating: 4.7,
        reviews: 2345,
        stock: 160,
        sku: "HC-BDDR-001",
        brand: "Briogeo",
        images: ["https://images.unsplash.com/photo-1599305090598-fe179d501227?w=600"],
        description: "Deep conditioning mask for damaged hair.",
      },
      {
        name: "Living Proof Perfect Hair Day Shampoo",
        category: "hair-care",
        price: 32.0,
        salePrice: 28.0,
        rating: 4.6,
        reviews: 3456,
        stock: 280,
        sku: "HC-LPPHDS-001",
        brand: "Living Proof",
        images: ["https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=600"],
        description: "Weightless shampoo that adds body and shine.",
        variants: [{ name: "Size", values: ["8 oz", "24 oz"] }],
      },
      {
        name: "T3 Cura Luxe Hair Dryer",
        category: "hair-care",
        price: 285.0,
        salePrice: 249.0,
        rating: 4.7,
        reviews: 1234,
        stock: 80,
        sku: "HC-T3CL-001",
        brand: "T3",
        images: ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600"],
        description: "Professional ionic hair dryer with digital technology.",
      },

      // Body Care - 8 products
      {
        name: "Sol de Janeiro Bum Bum Cream",
        category: "body-care",
        price: 55.0,
        salePrice: 48.0,
        rating: 4.8,
        reviews: 5678,
        stock: 250,
        sku: "BC-SDJBBB-001",
        brand: "Sol de Janeiro",
        featured: true,
        images: ["https://images.unsplash.com/photo-1570194065650-d99fb4b38b17?w=600"],
        description: "Fast-absorbing body cream with cupuaçu butter for smooth, firm-looking skin.",
      },
      {
        name: "Nécessaire The Body Wash",
        category: "body-care",
        price: 32.0,
        salePrice: 28.0,
        rating: 4.7,
        reviews: 2345,
        stock: 300,
        sku: "BC-NTBW-001",
        brand: "Nécessaire",
        images: ["https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600"],
        description: "Clean body wash with niacinamide and vitamins for soft, smooth skin.",
        variants: [{ name: "Scent", values: ["Eucalyptus", "Sandalwood", "Bergamot", "Fragrance Free"] }],
      },
      {
        name: "Kopari Coconut Melt",
        category: "body-care",
        price: 45.0,
        salePrice: 38.0,
        rating: 4.6,
        reviews: 1234,
        stock: 200,
        sku: "BC-KCM-001",
        brand: "Kopari",
        images: ["https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600"],
        description: "100% organic coconut oil multi-purpose beauty balm.",
      },
      {
        name: "First Aid Beauty Ultra Repair Cream",
        category: "body-care",
        price: 38.0,
        salePrice: 32.0,
        rating: 4.8,
        reviews: 4567,
        stock: 280,
        sku: "BC-FABURC-001",
        brand: "First Aid Beauty",
        images: ["https://images.unsplash.com/photo-1570194065650-d99fb4b38b17?w=600"],
        description: "Intense hydration for dry, distressed skin.",
        variants: [{ name: "Size", values: ["2 oz", "6 oz", "14 oz"] }],
      },
      {
        name: "Jergens Natural Glow Moisturizer",
        category: "body-care",
        price: 12.99,
        salePrice: 9.99,
        rating: 4.4,
        reviews: 6789,
        stock: 400,
        sku: "BC-JNGM-001",
        brand: "Jergens",
        images: ["https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600"],
        description: "Daily moisturizer that gradually builds a natural-looking tan.",
        variants: [{ name: "Shade", values: ["Fair to Medium", "Medium to Tan"] }],
      },
      {
        name: "Lush Sleepy Body Lotion",
        category: "body-care",
        price: 34.95,
        salePrice: 29.95,
        rating: 4.7,
        reviews: 3456,
        stock: 180,
        sku: "BC-LSBL-001",
        brand: "Lush",
        images: ["https://images.unsplash.com/photo-1570194065650-d99fb4b38b17?w=600"],
        description: "Relaxing lavender body lotion for bedtime.",
      },
      {
        name: "Herbivore Coco Rose Body Polish",
        category: "body-care",
        price: 38.0,
        salePrice: 32.0,
        rating: 4.6,
        reviews: 1876,
        stock: 150,
        sku: "BC-HCRBP-001",
        brand: "Herbivore",
        images: ["https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600"],
        description: "Coconut oil and Moroccan rose body scrub.",
      },
      {
        name: "Dove Exfoliating Body Polish",
        category: "body-care",
        price: 8.99,
        salePrice: 6.99,
        rating: 4.5,
        reviews: 5678,
        stock: 500,
        sku: "BC-DEBP-001",
        brand: "Dove",
        images: ["https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600"],
        description: "Gentle exfoliating body scrub with crushed macadamia.",
      },

      // Tools & Accessories - 8 products
      {
        name: "Beautyblender Original",
        category: "tools-accessories",
        price: 22.0,
        salePrice: 20.0,
        rating: 4.7,
        reviews: 8765,
        stock: 500,
        sku: "TA-BBO-001",
        brand: "Beautyblender",
        images: ["https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600"],
        description: "The original edgeless makeup sponge for flawless application.",
      },
      {
        name: "PMD Clean Pro",
        category: "tools-accessories",
        price: 199.0,
        salePrice: 179.0,
        rating: 4.8,
        reviews: 2345,
        stock: 100,
        sku: "TA-PMDCP-001",
        brand: "PMD",
        featured: true,
        images: ["https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600"],
        description: "Smart facial cleansing device with SonicGlow technology and ActiveWarmth.",
      },
      {
        name: "GHD Platinum+ Styler",
        category: "tools-accessories",
        price: 299.0,
        salePrice: 279.0,
        rating: 4.9,
        reviews: 3456,
        stock: 80,
        sku: "TA-GHDPS-001",
        brand: "GHD",
        featured: true,
        images: ["https://images.unsplash.com/photo-1590439471364-192aa70c0b53?w=600"],
        description: "Ultra-zone predictive technology for 70% healthier hair with every style.",
      },
      {
        name: "NuFACE Trinity Facial Toning",
        category: "tools-accessories",
        price: 395.0,
        salePrice: 339.0,
        rating: 4.7,
        reviews: 1234,
        stock: 60,
        sku: "TA-NFT-001",
        brand: "NuFACE",
        images: ["https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600"],
        description: "FDA-cleared microcurrent facial toning device for lifted, toned, contoured look.",
      },
      {
        name: "Real Techniques Brush Set",
        category: "tools-accessories",
        price: 19.99,
        salePrice: 16.99,
        rating: 4.6,
        reviews: 6789,
        stock: 400,
        sku: "TA-RTBS-001",
        brand: "Real Techniques",
        images: ["https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600"],
        description: "5-piece brush set for flawless makeup application.",
      },
      {
        name: "Foreo Luna 4",
        category: "tools-accessories",
        price: 279.0,
        salePrice: 249.0,
        rating: 4.7,
        reviews: 2345,
        stock: 120,
        sku: "TA-FL4-001",
        brand: "Foreo",
        images: ["https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600"],
        description: "Smart facial cleansing and firming massage device.",
      },
      {
        name: "TheraFace PRO",
        category: "tools-accessories",
        price: 399.0,
        salePrice: 349.0,
        rating: 4.6,
        reviews: 876,
        stock: 50,
        sku: "TA-TFP-001",
        brand: "Therabody",
        images: ["https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600"],
        description: "All-in-one facial health device with LED, microcurrent, and cleansing.",
      },
      {
        name: "Tweezerman Slant Tweezer",
        category: "tools-accessories",
        price: 25.0,
        salePrice: 22.0,
        rating: 4.8,
        reviews: 5678,
        stock: 350,
        sku: "TA-TST-001",
        brand: "Tweezerman",
        images: ["https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600"],
        description: "Precision stainless steel slant tweezer.",
      },
    ],
  },
];

async function seedEnterprise() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log("✅ Connected to MongoDB");

    // Clear existing data
    console.log("🗑️  Clearing existing data...");
    await Promise.all([Tenant.deleteMany({}), User.deleteMany({}), Category.deleteMany({}), Product.deleteMany({}), Order.deleteMany({})]);

    // Create super admin (you/Synexon - platform owner)
    console.log("👤 Creating super admin...");
    const superAdmin = await User.create({
      email: "superadmin@retailx.com",
      password: "SuperAdmin@123456",
      firstName: "Super",
      lastName: "Admin",
      role: "super_admin",
      status: "active",
      emailVerified: true,
    });

    // Seed each store
    for (const data of storeData) {
      console.log(`\n🏪 Creating store: ${data.name}`);

      // Create store owner
      const owner = await User.create({
        email: data.owner.email,
        password: data.owner.password,
        firstName: data.owner.firstName,
        lastName: data.owner.lastName,
        role: "store_owner",
        status: "active",
        emailVerified: true,
      });

      // Create tenant/store
      const tenant = await Tenant.create({
        name: data.name,
        slug: data.slug,
        description: data.description,
        industry: data.industry,
        domains: { subdomain: data.slug },
        branding: {
          primaryColor: data.branding.primaryColor,
          secondaryColor: data.branding.secondaryColor,
          accentColor: data.branding.accentColor,
        },
        contact: {
          email: `hello@${data.slug}.com`,
          phone: "+1 (555) 123-4567",
        },
        settings: {
          currency: "USD",
          currencySymbol: "$",
          taxRate: 8.875,
          shippingEnabled: true,
          guestCheckout: true,
          reviewsEnabled: true,
        },
        shipping: {
          methods: [
            { name: "Standard Shipping", description: "5-7 business days", price: 5.99, estimatedDays: "5-7", enabled: true },
            { name: "Express Shipping", description: "2-3 business days", price: 12.99, estimatedDays: "2-3", enabled: true },
            { name: "Next Day Delivery", description: "Next business day", price: 24.99, estimatedDays: "1", enabled: true },
          ],
          freeShippingThreshold: 50,
        },
        status: "active",
        createdBy: superAdmin._id,
      });

      // Update owner with tenant reference
      owner.tenant = tenant._id;
      await owner.save();

      // Create categories
      console.log(`  📁 Creating ${data.categories.length} categories...`);
      const categoryMap = {};
      for (let i = 0; i < data.categories.length; i++) {
        const cat = data.categories[i];
        const category = await Category.create({
          tenant: tenant._id,
          name: cat.name,
          slug: cat.slug,
          description: `${cat.name} collection`,
          image: cat.image,
          displayOrder: i,
          status: "active",
        });
        categoryMap[cat.slug] = category._id;
      }

      // Create products
      console.log(`  📦 Creating ${data.products.length} products...`);
      for (const prod of data.products) {
        const productSlug = prod.name
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, "-")
          .replace(/(^-|-$)/g, "");

        // Prepare images array
        const images = prod.images.map((url, idx) => ({
          url,
          alt: prod.name,
          isPrimary: idx === 0,
          displayOrder: idx,
        }));

        // Prepare variants
        const hasVariants = prod.variants && prod.variants.length > 0;
        const variantOptions = hasVariants ? prod.variants : [];

        await Product.create({
          tenant: tenant._id,
          name: prod.name,
          slug: productSlug,
          description: prod.description,
          shortDescription: prod.description?.substring(0, 150),
          category: categoryMap[prod.category],
          brand: prod.brand,
          images,
          pricing: {
            basePrice: prod.price,
            salePrice: prod.salePrice,
            costPrice: prod.price * 0.6,
            currency: "USD",
            taxable: true,
          },
          inventory: {
            sku: prod.sku,
            quantity: prod.stock,
            lowStockThreshold: 10,
            trackQuantity: true,
            stockStatus: prod.stock > 10 ? "in_stock" : prod.stock > 0 ? "low_stock" : "out_of_stock",
          },
          hasVariants,
          variantOptions,
          ratings: {
            average: prod.rating,
            count: prod.reviews,
          },
          featured: prod.featured || false,
          status: "active",
          visibility: "visible",
          seo: {
            title: prod.name,
            description: prod.description?.substring(0, 160),
          },
        });
      }

      console.log(`  ✅ Store "${data.name}" created with ${data.products.length} products`);
    }

    console.log("\n🎉 Enterprise seed completed successfully!");
    console.log("\n📋 Test Credentials:");
    console.log("   Platform Admin: admin@retailx.com / Admin@123456");
    console.log("   Urban Fashion: owner@urbanfashion.com / Owner@123456");
    console.log("   TechHub: owner@techhub.com / Owner@123456");
    console.log("   GlowBeauty: owner@glowbeauty.com / Owner@123456");

    console.log("\n📊 Statistics:");
    const totalProducts = storeData.reduce((sum, store) => sum + store.products.length, 0);
    const totalCategories = storeData.reduce((sum, store) => sum + store.categories.length, 0);
    console.log(`   Total Stores: ${storeData.length}`);
    console.log(`   Total Categories: ${totalCategories}`);
    console.log(`   Total Products: ${totalProducts}`);

    process.exit(0);
  } catch (error) {
    console.error("❌ Seed failed:", error);
    process.exit(1);
  }
}

seedEnterprise();
