require("dotenv").config();
const mongoose = require("mongoose");
const bcrypt = require("bcryptjs");
const config = require("../config");
const { Tenant, User, Category, Product, Order } = require("../models");
const logger = require("../utils/logger");

const seedData = async () => {
  try {
    // Connect to database
    await mongoose.connect(config.mongodb.uri, config.mongodb.options);
    logger.info("Connected to MongoDB");

    // Clear existing data
    logger.info("Clearing existing data...");
    await Promise.all([Tenant.deleteMany({}), User.deleteMany({}), Category.deleteMany({}), Product.deleteMany({}), Order.deleteMany({})]);

    // Create Super Admin (RetailX Platform Owner - Highest Level)
    // This is YOU (Synexon) - the only platform-level user
    logger.info("Creating super admin...");
    const superAdmin = await User.create({
      email: "superadmin@retailx.com",
      password: "SuperAdmin@123456",
      firstName: "RetailX",
      lastName: "Super Admin",
      role: "super_admin",
      tenant: null,
      status: "active",
      emailVerified: true,
    });
    logger.info("Super admin created: " + superAdmin.email);

    // Note: Store owners are created per-store below
    // Each store owner represents a CUSTOMER who purchased RetailX from you


    // ═══════════════════════════════════════════════════════════════════════
    // STORE 2: FRESHMART GROCERY (Supermarket / Grocery)
    // ═══════════════════════════════════════════════════════════════════════
    logger.info("Creating FreshMart Grocery store...");

    const groceryStore = await Tenant.create({
      name: "FreshMart Grocery",
      slug: "fresh-mart",
      description: "Fresh groceries and daily essentials delivered to your door",
      industry: "grocery",
      domains: { subdomain: "fresh-mart" },
      branding: {
        logo: "/uploads/logos/fresh-mart.png",
        primaryColor: "#4CAF50",
        secondaryColor: "#388E3C",
        accentColor: "#8BC34A",
        fontFamily: "Inter",
      },
      contact: {
        email: "hello@freshmart.com",
        phone: "+1 (555) 234-5678",
        address: { street: "456 Market St", city: "San Francisco", state: "CA", zipCode: "94102", country: "US" },
      },
      settings: { currency: "USD", currencySymbol: "$", taxRate: 0, shippingEnabled: true, guestCheckout: true },
      features: { productVariants: true, productSKU: true, productWeight: true, productExpiryDate: true, productNutrition: true, productTags: true },
      shipping: {
        methods: [
          { name: "Same Day Delivery", description: "Order before 2 PM", price: 4.99, estimatedDays: "Same day", enabled: true },
          { name: "Scheduled Delivery", description: "Pick your time slot", price: 2.99, estimatedDays: "1-2", enabled: true },
        ],
        freeShippingThreshold: 50,
      },
      status: "active",
      createdBy: superAdmin._id,
    });

    const groceryOwner = await User.create({
      email: "owner@freshmart.com",
      password: "Owner@123456",
      firstName: "Mike",
      lastName: "Fresh",
      role: "store_owner",
      tenant: groceryStore._id,
      status: "active",
      emailVerified: true,
    });

    // Grocery Categories
    const groceryCategories = {
      fruits: await Category.create({ tenant: groceryStore._id, name: "Fruits & Vegetables", slug: "fruits-vegetables", description: "Fresh produce daily", displayOrder: 1, showInMenu: true, showInHomepage: true, status: "active", createdBy: groceryOwner._id }),
      dairy: await Category.create({ tenant: groceryStore._id, name: "Dairy & Eggs", slug: "dairy-eggs", description: "Milk, cheese, eggs and more", displayOrder: 2, showInMenu: true, showInHomepage: true, status: "active", createdBy: groceryOwner._id }),
      bakery: await Category.create({ tenant: groceryStore._id, name: "Bakery", slug: "bakery", description: "Fresh baked goods", displayOrder: 3, showInMenu: true, showInHomepage: true, status: "active", createdBy: groceryOwner._id }),
      pantry: await Category.create({ tenant: groceryStore._id, name: "Pantry Essentials", slug: "pantry", description: "Rice, pasta, oils and spices", displayOrder: 4, showInMenu: true, showInHomepage: true, status: "active", createdBy: groceryOwner._id }),
      beverages: await Category.create({ tenant: groceryStore._id, name: "Beverages", slug: "beverages", description: "Drinks and juices", displayOrder: 5, showInMenu: true, showInHomepage: true, status: "active", createdBy: groceryOwner._id }),
    };

    // Grocery Products
    const groceryProducts = [
      {
        tenant: groceryStore._id,
        name: "Organic Bananas",
        slug: "organic-bananas",
        description: "Fresh organic bananas, perfect for smoothies, snacks, or baking. Rich in potassium and naturally sweet.",
        shortDescription: "Fresh organic bananas - 1 bunch",
        category: groceryCategories.fruits._id,
        brand: "Nature Best",
        images: [{ url: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=800", alt: "Organic Bananas", isPrimary: true }],
        pricing: { basePrice: 2.99, currency: "USD" },
        inventory: { sku: "FM-FR-001", quantity: 200, trackQuantity: true },
        tags: ["organic", "fruits", "banana", "fresh"],
        ratings: { average: 4.6, count: 234 },
        status: "active",
        isFeatured: true,
        createdBy: groceryOwner._id,
      },
      {
        tenant: groceryStore._id,
        name: "Fresh Avocados",
        slug: "fresh-avocados",
        description: "Perfectly ripe Hass avocados. Great for guacamole, toast, or salads.",
        shortDescription: "Ripe Hass avocados - Pack of 4",
        category: groceryCategories.fruits._id,
        brand: "Farm Fresh",
        images: [{ url: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=800", alt: "Avocados", isPrimary: true }],
        pricing: { basePrice: 5.99, currency: "USD" },
        inventory: { sku: "FM-FR-002", quantity: 150, trackQuantity: true },
        tags: ["avocado", "fruits", "fresh", "healthy"],
        ratings: { average: 4.7, count: 189 },
        status: "active",
        isFeatured: true,
        createdBy: groceryOwner._id,
      },
      {
        tenant: groceryStore._id,
        name: "Organic Whole Milk",
        slug: "organic-whole-milk",
        description: "Fresh organic whole milk from grass-fed cows. No antibiotics or hormones.",
        shortDescription: "Organic whole milk - 1 gallon",
        category: groceryCategories.dairy._id,
        brand: "Happy Farms",
        images: [{ url: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=800", alt: "Organic Milk", isPrimary: true }],
        pricing: { basePrice: 6.49, currency: "USD" },
        inventory: { sku: "FM-DA-001", quantity: 100, trackQuantity: true },
        tags: ["organic", "milk", "dairy", "fresh"],
        ratings: { average: 4.8, count: 156 },
        status: "active",
        isFeatured: true,
        createdBy: groceryOwner._id,
      },
      {
        tenant: groceryStore._id,
        name: "Farm Fresh Eggs",
        slug: "farm-fresh-eggs",
        description: "Large brown eggs from free-range hens. Perfect for breakfast or baking.",
        shortDescription: "Free-range eggs - Dozen",
        category: groceryCategories.dairy._id,
        brand: "Happy Hens",
        images: [{ url: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=800", alt: "Farm Eggs", isPrimary: true }],
        pricing: { basePrice: 5.99, salePrice: 4.99, currency: "USD" },
        inventory: { sku: "FM-DA-002", quantity: 80, trackQuantity: true },
        tags: ["eggs", "organic", "free-range", "breakfast"],
        ratings: { average: 4.9, count: 245 },
        status: "active",
        isFeatured: true,
        isOnSale: true,
        createdBy: groceryOwner._id,
      },
      {
        tenant: groceryStore._id,
        name: "Artisan Sourdough Bread",
        slug: "artisan-sourdough",
        description: "Freshly baked artisan sourdough bread. Crusty exterior with soft, tangy interior.",
        shortDescription: "Fresh baked sourdough loaf",
        category: groceryCategories.bakery._id,
        brand: "Artisan Bakes",
        images: [{ url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800", alt: "Sourdough Bread", isPrimary: true }],
        pricing: { basePrice: 4.99, currency: "USD" },
        inventory: { sku: "FM-BK-001", quantity: 50, trackQuantity: true },
        tags: ["bread", "sourdough", "artisan", "bakery"],
        ratings: { average: 4.7, count: 123 },
        status: "active",
        isFeatured: true,
        createdBy: groceryOwner._id,
      },
      {
        tenant: groceryStore._id,
        name: "Extra Virgin Olive Oil",
        slug: "extra-virgin-olive-oil",
        description: "Premium cold-pressed extra virgin olive oil from Italian olives. Perfect for cooking and salads.",
        shortDescription: "Italian EVOO - 500ml",
        category: groceryCategories.pantry._id,
        brand: "Mediterranean Gold",
        images: [{ url: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800", alt: "Olive Oil", isPrimary: true }],
        pricing: { basePrice: 12.99, currency: "USD" },
        inventory: { sku: "FM-PT-001", quantity: 75, trackQuantity: true },
        tags: ["olive oil", "cooking", "pantry", "italian"],
        ratings: { average: 4.8, count: 98 },
        status: "active",
        isFeatured: true,
        createdBy: groceryOwner._id,
      },
      {
        tenant: groceryStore._id,
        name: "Organic Orange Juice",
        slug: "organic-orange-juice",
        description: "Freshly squeezed organic orange juice. No added sugar or preservatives.",
        shortDescription: "Fresh squeezed OJ - 64oz",
        category: groceryCategories.beverages._id,
        brand: "Sunrise Farms",
        images: [{ url: "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=800", alt: "Orange Juice", isPrimary: true }],
        pricing: { basePrice: 7.99, salePrice: 6.49, currency: "USD" },
        inventory: { sku: "FM-BV-001", quantity: 60, trackQuantity: true },
        tags: ["juice", "orange", "organic", "beverages"],
        ratings: { average: 4.5, count: 87 },
        status: "active",
        isFeatured: true,
        isOnSale: true,
        createdBy: groceryOwner._id,
      },
    ];

    await Product.insertMany(groceryProducts);

    // ═══════════════════════════════════════════════════════════════════════
    // STORE 10: GLAMOUR HAIR STUDIO (Hair Salon Business)
    // ═══════════════════════════════════════════════════════════════════════
    logger.info("Creating Glamour Hair Studio...");

    const hairSalonStore = await Tenant.create({
      name: "Glamour Hair Studio",
      slug: "glamour-hair",
      description: "Professional hair salon - cuts, styling, coloring & treatments",
      industry: "wellness",
      businessType: "services",
      serviceSettings: {
        appointmentRequired: true,
        bookingLeadTime: 24,
        cancellationPolicy: "Please cancel at least 24 hours in advance",
        sessionBased: true,
        durationUnit: "minutes",
      },
      domains: { subdomain: "glamour-hair" },
      branding: {
        logo: "/uploads/logos/glamour-hair.png",
        primaryColor: "#E91E63",
        secondaryColor: "#C2185B",
        accentColor: "#F48FB1",
        fontFamily: "Playfair Display",
      },
      contact: {
        email: "hello@glamourhair.com",
        phone: "+1 (555) 111-2222",
        address: { street: "123 Style Street", city: "Los Angeles", state: "CA", zipCode: "90001", country: "US" },
      },
      settings: { currency: "USD", currencySymbol: "$", taxRate: 9.5, shippingEnabled: false, guestCheckout: true },
      features: { productVariants: true, productSKU: true, productBrand: true, productTags: true, productDuration: true },
      shipping: { methods: [], freeShippingThreshold: 0 },
      status: "active",
      createdBy: superAdmin._id,
    });

    const hairSalonOwner = await User.create({
      email: "owner@glamourhair.com",
      password: "Owner@123456",
      firstName: "Maria",
      lastName: "Styles",
      role: "store_owner",
      tenant: hairSalonStore._id,
      status: "active",
      emailVerified: true,
    });

    // Hair Salon Categories
    const hairCategories = {
      haircuts: await Category.create({
        tenant: hairSalonStore._id,
        name: "Haircuts & Styling",
        slug: "haircuts-styling",
        description: "Professional haircuts and styling services for all hair types",
        image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800",
        displayOrder: 1,
        showInMenu: true,
        showInHomepage: true,
        status: "active",
        createdBy: hairSalonOwner._id,
      }),
      coloring: await Category.create({
        tenant: hairSalonStore._id,
        name: "Hair Coloring",
        slug: "hair-coloring",
        description: "Full color, highlights, balayage, ombre and creative coloring",
        image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800",
        displayOrder: 2,
        showInMenu: true,
        showInHomepage: true,
        status: "active",
        createdBy: hairSalonOwner._id,
      }),
      treatments: await Category.create({
        tenant: hairSalonStore._id,
        name: "Hair Treatments",
        slug: "hair-treatments",
        description: "Keratin, deep conditioning, scalp treatments and hair repair",
        image: "https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=800",
        displayOrder: 3,
        showInMenu: true,
        showInHomepage: true,
        status: "active",
        createdBy: hairSalonOwner._id,
      }),
      bridal: await Category.create({
        tenant: hairSalonStore._id,
        name: "Bridal & Special Events",
        slug: "bridal-events",
        description: "Wedding hair, prom styles and special occasion styling",
        image: "https://images.unsplash.com/photo-1519741497674-611481863552?w=800",
        displayOrder: 4,
        showInMenu: true,
        showInHomepage: true,
        status: "active",
        createdBy: hairSalonOwner._id,
      }),
      products: await Category.create({
        tenant: hairSalonStore._id,
        name: "Hair Products",
        slug: "hair-products",
        description: "Professional shampoos, conditioners and styling products",
        image: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=800",
        displayOrder: 5,
        showInMenu: true,
        showInHomepage: true,
        status: "active",
        createdBy: hairSalonOwner._id,
      }),
    };

    // Hair Salon Products/Services
    const hairProducts = [
      {
        tenant: hairSalonStore._id,
        name: "Women's Haircut & Blow Dry",
        slug: "womens-haircut-blow-dry",
        description: "Professional women's haircut with consultation, shampoo, conditioning, precision cut, and professional blow-dry styling. Our expert stylists create the perfect look for your face shape and lifestyle.",
        shortDescription: "Professional haircut with styling",
        category: hairCategories.haircuts._id,
        brand: "Glamour Studio",
        images: [{ url: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800", alt: "Women's Haircut", isPrimary: true }],
        pricing: { basePrice: 65.0, currency: "USD" },
        inventory: { sku: "GH-HC-001", quantity: 999, trackQuantity: false },
        tags: ["haircut", "women", "styling", "blow dry"],
        ratings: { average: 4.9, count: 342 },
        status: "active",
        isFeatured: true,
        createdBy: hairSalonOwner._id,
      },
      {
        tenant: hairSalonStore._id,
        name: "Men's Haircut & Style",
        slug: "mens-haircut-style",
        description: "Classic or modern men's haircut including consultation, wash, precision cut, and styling with premium products. Includes hot towel service and neck trim.",
        shortDescription: "Men's precision haircut",
        category: hairCategories.haircuts._id,
        brand: "Glamour Studio",
        images: [{ url: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800", alt: "Men's Haircut", isPrimary: true }],
        pricing: { basePrice: 35.0, currency: "USD" },
        inventory: { sku: "GH-HC-002", quantity: 999, trackQuantity: false },
        tags: ["haircut", "men", "barber", "styling"],
        ratings: { average: 4.8, count: 256 },
        status: "active",
        isFeatured: true,
        createdBy: hairSalonOwner._id,
      },
      {
        tenant: hairSalonStore._id,
        name: "Full Hair Color",
        slug: "full-hair-color",
        description: "Complete hair coloring service with premium ammonia-free dyes. Includes color consultation, strand test, application, processing, and finishing style. Long-lasting vibrant color.",
        shortDescription: "Complete hair color transformation",
        category: hairCategories.coloring._id,
        brand: "Glamour Studio",
        images: [{ url: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800", alt: "Hair Coloring", isPrimary: true }],
        pricing: { basePrice: 120.0, salePrice: 99.0, currency: "USD" },
        inventory: { sku: "GH-CL-001", quantity: 999, trackQuantity: false },
        tags: ["hair color", "dye", "color change", "salon"],
        ratings: { average: 4.9, count: 198 },
        status: "active",
        isFeatured: true,
        isOnSale: true,
        createdBy: hairSalonOwner._id,
      },
      {
        tenant: hairSalonStore._id,
        name: "Balayage Highlights",
        slug: "balayage-highlights",
        description: "Hand-painted balayage highlights for a natural, sun-kissed look. Creates beautiful dimension with seamless blending. Includes toner and styling.",
        shortDescription: "Natural hand-painted highlights",
        category: hairCategories.coloring._id,
        brand: "Glamour Studio",
        images: [{ url: "https://images.unsplash.com/photo-1605980776566-0486c3ac7617?w=800", alt: "Balayage", isPrimary: true }],
        pricing: { basePrice: 180.0, currency: "USD" },
        inventory: { sku: "GH-CL-002", quantity: 999, trackQuantity: false },
        tags: ["balayage", "highlights", "ombre", "natural"],
        ratings: { average: 4.9, count: 167 },
        status: "active",
        isFeatured: true,
        createdBy: hairSalonOwner._id,
      },
      {
        tenant: hairSalonStore._id,
        name: "Keratin Smoothing Treatment",
        slug: "keratin-smoothing-treatment",
        description: "Brazilian keratin treatment for frizz-free, silky smooth hair lasting 3-4 months. Includes deep cleanse, keratin application, heat sealing, and home care instructions.",
        shortDescription: "Professional keratin smoothing",
        category: hairCategories.treatments._id,
        brand: "Glamour Studio",
        images: [{ url: "https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=800", alt: "Keratin Treatment", isPrimary: true }],
        pricing: { basePrice: 250.0, salePrice: 199.0, currency: "USD" },
        inventory: { sku: "GH-TR-001", quantity: 999, trackQuantity: false },
        tags: ["keratin", "smoothing", "frizz free", "treatment"],
        ratings: { average: 4.8, count: 145 },
        status: "active",
        isFeatured: true,
        isOnSale: true,
        createdBy: hairSalonOwner._id,
      },
      {
        tenant: hairSalonStore._id,
        name: "Bridal Hair Styling",
        slug: "bridal-hair-styling",
        description: "Complete bridal hair styling including trial session, wedding day styling, and touch-ups. Updos, half-up styles, or flowing curls. Includes hair accessories placement.",
        shortDescription: "Complete bridal hair package",
        category: hairCategories.bridal._id,
        brand: "Glamour Studio",
        images: [{ url: "https://images.unsplash.com/photo-1519741497674-611481863552?w=800", alt: "Bridal Hair", isPrimary: true }],
        pricing: { basePrice: 350.0, currency: "USD" },
        inventory: { sku: "GH-BR-001", quantity: 999, trackQuantity: false },
        tags: ["bridal", "wedding", "updo", "special event"],
        ratings: { average: 5.0, count: 89 },
        status: "active",
        isFeatured: true,
        createdBy: hairSalonOwner._id,
      },
      {
        tenant: hairSalonStore._id,
        name: "Professional Shampoo & Conditioner Set",
        slug: "professional-shampoo-conditioner",
        description: "Salon-quality shampoo and conditioner duo. Sulfate-free formula for color-treated hair. Restores moisture and adds shine. 16oz each.",
        shortDescription: "Salon shampoo & conditioner duo",
        category: hairCategories.products._id,
        brand: "Glamour Pro",
        images: [{ url: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=800", alt: "Hair Products", isPrimary: true }],
        pricing: { basePrice: 45.0, currency: "USD" },
        inventory: { sku: "GH-PR-001", quantity: 50, trackQuantity: true },
        tags: ["shampoo", "conditioner", "hair care", "professional"],
        ratings: { average: 4.7, count: 123 },
        status: "active",
        isFeatured: true,
        createdBy: hairSalonOwner._id,
      },
    ];

    await Product.insertMany(hairProducts);

    // ═══════════════════════════════════════════════════════════════════════
    // STORE 11: TRANQUIL TOUCH SPA (Massage Parlour Business)
    // ═══════════════════════════════════════════════════════════════════════
    logger.info("Creating Tranquil Touch Spa...");

    const massageStore = await Tenant.create({
      name: "Tranquil Touch Spa",
      slug: "tranquil-spa",
      description: "Professional massage therapy & body treatments for wellness and relaxation",
      industry: "wellness",
      businessType: "services",
      serviceSettings: {
        appointmentRequired: true,
        bookingLeadTime: 2,
        cancellationPolicy: "Please cancel at least 24 hours in advance for a full refund",
        sessionBased: true,
        durationUnit: "minutes",
      },
      domains: { subdomain: "tranquil-spa" },
      branding: {
        logo: "/uploads/logos/tranquil-spa.png",
        primaryColor: "#00897B",
        secondaryColor: "#00695C",
        accentColor: "#4DB6AC",
        fontFamily: "Lora",
      },
      contact: {
        email: "hello@tranquilspa.com",
        phone: "+1 (555) 333-4444",
        address: { street: "456 Serenity Lane", city: "San Francisco", state: "CA", zipCode: "94102", country: "US" },
      },
      settings: { currency: "USD", currencySymbol: "$", taxRate: 8.5, shippingEnabled: false, guestCheckout: true },
      features: {
        productVariants: true,
        productSKU: true,
        productBrand: true,
        productTags: true,
        productDuration: true,
        // Service business features - NO PAYMENT, BOOKING ONLY
        paymentEnabled: false,
        cartEnabled: false,
        bookingEnabled: true,
        guestCheckoutEnabled: true,
        shippingEnabled: false,
        inventoryEnabled: false,
        paymentProviders: {
          stripe: false,
          paypal: false,
          razorpay: false,
          cod: false,
          bankTransfer: false,
        },
        bookingRequiresPayment: false,
        bookingAllowCancellation: true,
        bookingReminderEnabled: true,
        customerAccountsEnabled: true,
        customerAccountRequired: false,
        reviewsEnabled: true,
        wishlistEnabled: false,
      },
      bookingSettings: {
        workingHours: {
          monday: { open: "09:00", close: "19:00", isOpen: true },
          tuesday: { open: "09:00", close: "19:00", isOpen: true },
          wednesday: { open: "09:00", close: "19:00", isOpen: true },
          thursday: { open: "09:00", close: "19:00", isOpen: true },
          friday: { open: "09:00", close: "20:00", isOpen: true },
          saturday: { open: "10:00", close: "18:00", isOpen: true },
          sunday: { open: "10:00", close: "16:00", isOpen: true },
        },
        slotDuration: 60,
        bufferTime: 15,
        advanceBookingDays: 30,
        phoneNumber: "+1 (555) 333-4444",
        confirmationMessage: "Thank you for choosing Tranquil Touch Spa! Please call us to confirm your booking. We look forward to helping you relax and rejuvenate.",
      },
      shipping: { methods: [], freeShippingThreshold: 0 },
      status: "active",
      createdBy: superAdmin._id,
    });

    const massageOwner = await User.create({
      email: "owner@tranquilspa.com",
      password: "Owner@123456",
      firstName: "Elena",
      lastName: "Calm",
      role: "store_owner",
      tenant: massageStore._id,
      status: "active",
      emailVerified: true,
    });

    // Massage Parlour Categories
    const massageCategories = {
      relaxation: await Category.create({
        tenant: massageStore._id,
        name: "Relaxation Massage",
        slug: "relaxation-massage",
        description: "Swedish, aromatherapy and gentle relaxation massages",
        image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800",
        displayOrder: 1,
        showInMenu: true,
        showInHomepage: true,
        status: "active",
        createdBy: massageOwner._id,
      }),
      therapeutic: await Category.create({
        tenant: massageStore._id,
        name: "Therapeutic Massage",
        slug: "therapeutic-massage",
        description: "Deep tissue, sports and medical massage therapy",
        image: "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=800",
        displayOrder: 2,
        showInMenu: true,
        showInHomepage: true,
        status: "active",
        createdBy: massageOwner._id,
      }),
      specialty: await Category.create({
        tenant: massageStore._id,
        name: "Specialty Treatments",
        slug: "specialty-treatments",
        description: "Hot stone, Thai massage and unique body treatments",
        image: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=800",
        displayOrder: 3,
        showInMenu: true,
        showInHomepage: true,
        status: "active",
        createdBy: massageOwner._id,
      }),
      couples: await Category.create({
        tenant: massageStore._id,
        name: "Couples & Packages",
        slug: "couples-packages",
        description: "Romantic couples massage and spa day packages",
        image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800",
        displayOrder: 4,
        showInMenu: true,
        showInHomepage: true,
        status: "active",
        createdBy: massageOwner._id,
      }),
      bodyTreatments: await Category.create({
        tenant: massageStore._id,
        name: "Body Treatments",
        slug: "body-treatments",
        description: "Body wraps, scrubs and detox treatments",
        image: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800",
        displayOrder: 5,
        showInMenu: true,
        showInHomepage: true,
        status: "active",
        createdBy: massageOwner._id,
      }),
    };

    // Massage Products/Services - Inspired by Siam Thai Massage
    const massageProducts = [
      {
        tenant: massageStore._id,
        name: "Traditional Thai Full Body Massage",
        slug: "traditional-thai-full-body-massage",
        description: "Experience the ancient art of Thai massage. Combining acupressure, stretching and yoga-like positions to bring mind and body into harmony. Relieves environmental stress and restores lightness and balance to your entire being.",
        shortDescription: "Traditional Thai massage for body & mind harmony",
        category: massageCategories.specialty._id,
        brand: "Tranquil Touch",
        images: [{ url: "https://images.unsplash.com/photo-1519824145371-296894a0daa9?w=800", alt: "Thai Full Body Massage", isPrimary: true }],
        pricing: { basePrice: 50.0, currency: "USD" },
        inventory: { sku: "TT-TH-001", quantity: 999, trackQuantity: false },
        hasVariants: true,
        variantOptions: [{ name: "Duration", values: ["60 min - $50", "90 min - $69"] }],
        tags: ["thai", "full body", "traditional", "acupressure", "stretching"],
        ratings: { average: 4.9, count: 456 },
        status: "active",
        isFeatured: true,
        createdBy: massageOwner._id,
      },
      {
        tenant: massageStore._id,
        name: "Ear Candle Treatment",
        slug: "ear-candle-treatment",
        description: "Experience an intensive feeling of pleasant warmth, comfort and deep relaxation. Our gentle ear candle treatment helps cleanse the ear canal while promoting a sense of well-being and tranquility.",
        shortDescription: "Gentle ear candling for relaxation & wellness",
        category: massageCategories.specialty._id,
        brand: "Tranquil Touch",
        images: [{ url: "https://images.unsplash.com/photo-1552693673-1bf958298935?w=800", alt: "Ear Candle Treatment", isPrimary: true }],
        pricing: { basePrice: 35.0, currency: "USD" },
        inventory: { sku: "TT-EC-001", quantity: 999, trackQuantity: false },
        hasVariants: true,
        variantOptions: [{ name: "Duration", values: ["30 min"] }],
        tags: ["ear candle", "relaxation", "wellness", "cleansing"],
        ratings: { average: 4.7, count: 189 },
        status: "active",
        isFeatured: true,
        createdBy: massageOwner._id,
      },
      {
        tenant: massageStore._id,
        name: "Aroma Relaxation Oil Full Body Massage",
        slug: "aroma-relaxation-oil-massage",
        description: "Bring your body into balance and feel the harmony. Our soothing aroma foot bath followed by a relaxing full body massage with premium aroma relaxation oils. Perfect for complete stress relief.",
        shortDescription: "Aromatic oil massage with foot bath",
        category: massageCategories.relaxation._id,
        brand: "Tranquil Touch",
        images: [{ url: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800", alt: "Aroma Oil Massage", isPrimary: true }],
        pricing: { basePrice: 50.0, currency: "USD" },
        inventory: { sku: "TT-AR-001", quantity: 999, trackQuantity: false },
        hasVariants: true,
        variantOptions: [{ name: "Duration", values: ["60 min - $50", "90 min - $69"] }],
        tags: ["aroma", "oil massage", "relaxation", "foot bath", "full body"],
        ratings: { average: 4.9, count: 312 },
        status: "active",
        isFeatured: true,
        createdBy: massageOwner._id,
      },
      {
        tenant: massageStore._id,
        name: "Back, Neck, Head & Face Massage",
        slug: "back-neck-head-face-massage",
        description: "Enjoy paradise in our massage studio and let your soul unwind. This relaxing back and neck massage followed by head and face massage targets the key stress areas to provide complete relief and rejuvenation.",
        shortDescription: "Targeted massage for back, neck, head & face",
        category: massageCategories.therapeutic._id,
        brand: "Tranquil Touch",
        images: [{ url: "https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=800", alt: "Back Neck Massage", isPrimary: true }],
        pricing: { basePrice: 28.0, currency: "USD" },
        inventory: { sku: "TT-BN-001", quantity: 999, trackQuantity: false },
        hasVariants: true,
        variantOptions: [{ name: "Duration", values: ["30 min"] }],
        tags: ["back", "neck", "head", "face", "targeted massage"],
        ratings: { average: 4.8, count: 267 },
        status: "active",
        isFeatured: true,
        createdBy: massageOwner._id,
      },
      {
        tenant: massageStore._id,
        name: "Foot Reflexology Massage",
        slug: "foot-reflexology-massage",
        description: "Treat yourself to a break from the stresses of life. Our soothing aroma foot bath followed by professional reflexology massage. Stimulates reflex points that correspond to different body organs and systems.",
        shortDescription: "Reflexology with aroma foot bath",
        category: massageCategories.specialty._id,
        brand: "Tranquil Touch",
        images: [{ url: "https://images.unsplash.com/photo-1519824145371-296894a0daa9?w=800", alt: "Foot Reflexology", isPrimary: true }],
        pricing: { basePrice: 28.0, currency: "USD" },
        inventory: { sku: "TT-FR-001", quantity: 999, trackQuantity: false },
        hasVariants: true,
        variantOptions: [{ name: "Duration", values: ["30 min"] }],
        tags: ["reflexology", "foot massage", "aroma bath", "relaxation"],
        ratings: { average: 4.9, count: 234 },
        status: "active",
        isFeatured: true,
        createdBy: massageOwner._id,
      },
      {
        tenant: massageStore._id,
        name: "Swedish Relaxation Massage",
        slug: "swedish-relaxation-massage",
        description: "Classic Swedish massage using long, flowing strokes to improve circulation, ease muscle tension, and promote deep relaxation. Perfect for stress relief and overall wellness. Includes aromatherapy oils.",
        shortDescription: "Classic relaxation massage",
        category: massageCategories.relaxation._id,
        brand: "Tranquil Touch",
        images: [{ url: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=800", alt: "Swedish Massage", isPrimary: true }],
        pricing: { basePrice: 85.0, currency: "USD" },
        inventory: { sku: "TT-RM-001", quantity: 999, trackQuantity: false },
        hasVariants: true,
        variantOptions: [{ name: "Duration", values: ["60 min", "90 min", "120 min"] }],
        tags: ["swedish", "relaxation", "massage", "stress relief"],
        ratings: { average: 4.9, count: 456 },
        status: "active",
        createdBy: massageOwner._id,
      },
      {
        tenant: massageStore._id,
        name: "Deep Tissue Therapeutic Massage",
        slug: "deep-tissue-massage",
        description: "Therapeutic massage targeting chronic muscle tension and pain. Focuses on deeper muscle layers to release knots, break up scar tissue, and restore mobility. Ideal for athletes and chronic pain sufferers.",
        shortDescription: "Therapeutic deep muscle therapy",
        category: massageCategories.therapeutic._id,
        brand: "Tranquil Touch",
        images: [{ url: "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=800", alt: "Deep Tissue", isPrimary: true }],
        pricing: { basePrice: 105.0, currency: "USD" },
        inventory: { sku: "TT-TM-001", quantity: 999, trackQuantity: false },
        hasVariants: true,
        variantOptions: [{ name: "Duration", values: ["60 min", "90 min"] }],
        tags: ["deep tissue", "therapeutic", "muscle pain", "sports"],
        ratings: { average: 4.8, count: 289 },
        status: "active",
        createdBy: massageOwner._id,
      },
      {
        tenant: massageStore._id,
        name: "Hot Stone Therapy",
        slug: "hot-stone-massage",
        description: "Luxurious massage using heated basalt stones. The warmth penetrates deep into muscles, melting tension and stress. Stones are placed on key points while massage techniques provide complete relaxation.",
        shortDescription: "Heated stone therapy massage",
        category: massageCategories.specialty._id,
        brand: "Tranquil Touch",
        images: [{ url: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=800", alt: "Hot Stone", isPrimary: true }],
        pricing: { basePrice: 125.0, currency: "USD" },
        inventory: { sku: "TT-SP-001", quantity: 999, trackQuantity: false },
        hasVariants: true,
        variantOptions: [{ name: "Duration", values: ["75 min", "90 min"] }],
        tags: ["hot stone", "luxury", "relaxation", "heat therapy"],
        ratings: { average: 4.9, count: 267 },
        status: "active",
        createdBy: massageOwner._id,
      },
      {
        tenant: massageStore._id,
        name: "Couples Romantic Package",
        slug: "couples-massage",
        description: "Romantic side-by-side massage experience for two. Share a private suite while trained therapists provide synchronized Swedish or deep tissue massage. Includes champagne and chocolates.",
        shortDescription: "Romantic massage for two",
        category: massageCategories.couples._id,
        brand: "Tranquil Touch",
        images: [{ url: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800", alt: "Couples Massage", isPrimary: true }],
        pricing: { basePrice: 200.0, salePrice: 175.0, currency: "USD" },
        inventory: { sku: "TT-CP-001", quantity: 999, trackQuantity: false },
        hasVariants: true,
        variantOptions: [{ name: "Duration", values: ["60 min", "90 min"] }],
        tags: ["couples", "romantic", "package", "special occasion"],
        ratings: { average: 5.0, count: 134 },
        status: "active",
        isOnSale: true,
        createdBy: massageOwner._id,
      },
      {
        tenant: massageStore._id,
        name: "Detox Body Wrap Treatment",
        slug: "detox-body-wrap",
        description: "Purifying full body treatment with mineral-rich clay and seaweed. Detoxifies, tightens skin, and reduces appearance of cellulite. Includes dry brushing, wrap, and hydrating lotion application.",
        shortDescription: "Detoxifying body wrap treatment",
        category: massageCategories.bodyTreatments._id,
        brand: "Tranquil Touch",
        images: [{ url: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800", alt: "Body Wrap", isPrimary: true }],
        pricing: { basePrice: 120.0, currency: "USD" },
        inventory: { sku: "TT-BT-001", quantity: 999, trackQuantity: false },
        tags: ["body wrap", "detox", "cellulite", "skin care"],
        ratings: { average: 4.7, count: 145 },
        status: "active",
        createdBy: massageOwner._id,
      },
    ];

    await Product.insertMany(massageProducts);

    // ═══════════════════════════════════════════════════════════════════════
    // STORE 12: HEALTHY FEET CLINIC (Podologie Business)
    // ═══════════════════════════════════════════════════════════════════════
    logger.info("Creating Healthy Feet Clinic...");

    const podologieStore = await Tenant.create({
      name: "Healthy Feet Clinic",
      slug: "healthy-feet",
      description: "Professional podology & foot care - healing, cleaning and therapeutic treatments",
      industry: "healthcare",
      businessType: "services",
      serviceSettings: {
        appointmentRequired: true,
        bookingLeadTime: 24,
        cancellationPolicy: "Please cancel at least 48 hours in advance",
        sessionBased: true,
        durationUnit: "minutes",
      },
      domains: { subdomain: "healthy-feet" },
      branding: {
        logo: "/uploads/logos/healthy-feet.png",
        primaryColor: "#1976D2",
        secondaryColor: "#1565C0",
        accentColor: "#42A5F5",
        fontFamily: "Roboto",
      },
      contact: {
        email: "hello@healthyfeet.com",
        phone: "+1 (555) 555-6666",
        address: { street: "789 Wellness Blvd", city: "San Diego", state: "CA", zipCode: "92101", country: "US" },
      },
      settings: { currency: "USD", currencySymbol: "$", taxRate: 7.75, shippingEnabled: true, guestCheckout: true },
      features: { productVariants: true, productSKU: true, productBrand: true, productTags: true, productDuration: true },
      shipping: {
        methods: [
          { name: "Standard Shipping", description: "5-7 business days", price: 5.99, estimatedDays: "5-7", enabled: true },
          { name: "Express Shipping", description: "2-3 business days", price: 11.99, estimatedDays: "2-3", enabled: true },
        ],
        freeShippingThreshold: 50,
      },
      status: "active",
      createdBy: superAdmin._id,
    });

    const podologieOwner = await User.create({
      email: "owner@healthyfeet.com",
      password: "Owner@123456",
      firstName: "Dr. Hans",
      lastName: "Weber",
      role: "store_owner",
      tenant: podologieStore._id,
      status: "active",
      emailVerified: true,
    });

    // Podologie Categories - Using verified Pexels foot care images
    const podologieCategories = {
      medicalCare: await Category.create({
        tenant: podologieStore._id,
        name: "Medical Foot Care",
        slug: "medical-foot-care",
        description: "Professional podiatry treatments for foot health conditions",
        image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800",
        displayOrder: 1,
        showInMenu: true,
        showInHomepage: true,
        status: "active",
        createdBy: podologieOwner._id,
      }),
      nailCare: await Category.create({
        tenant: podologieStore._id,
        name: "Nail Care & Treatment",
        slug: "nail-care-treatment",
        description: "Ingrown toenail, fungal treatment and nail correction",
        image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800",
        displayOrder: 2,
        showInMenu: true,
        showInHomepage: true,
        status: "active",
        createdBy: podologieOwner._id,
      }),
      diabeticCare: await Category.create({
        tenant: podologieStore._id,
        name: "Diabetic Foot Care",
        slug: "diabetic-foot-care",
        description: "Specialized care for diabetic patients",
        image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800",
        displayOrder: 3,
        showInMenu: true,
        showInHomepage: true,
        status: "active",
        createdBy: podologieOwner._id,
      }),
      reflexology: await Category.create({
        tenant: podologieStore._id,
        name: "Reflexology & Wellness",
        slug: "reflexology-wellness",
        description: "Foot reflexology and therapeutic foot massage",
        image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800",
        displayOrder: 4,
        showInMenu: true,
        showInHomepage: true,
        status: "active",
        createdBy: podologieOwner._id,
      }),
      footProducts: await Category.create({
        tenant: podologieStore._id,
        name: "Foot Care Products",
        slug: "foot-care-products",
        description: "Creams, orthotic insoles and foot care accessories",
        image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800",
        displayOrder: 5,
        showInMenu: true,
        showInHomepage: true,
        status: "active",
        createdBy: podologieOwner._id,
      }),
    };

    // Podologie Products/Services - Using foot massage/reflexology specific images
    const podologieProducts = [
      {
        tenant: podologieStore._id,
        name: "Medical Pedicure",
        slug: "medical-pedicure",
        description: "Comprehensive podology treatment by certified podiatrist. Includes foot examination, nail trimming and filing, callus and corn removal, cuticle care, and moisturizing treatment. Medical-grade hygiene standards.",
        shortDescription: "Professional medical foot care",
        category: podologieCategories.medicalCare._id,
        brand: "Healthy Feet",
        images: [{ url: "https://images.unsplash.com/photo-1519824145371-296894a0daa9?w=800", alt: "Medical Pedicure", isPrimary: true }],
        pricing: { basePrice: 75.0, currency: "USD" },
        inventory: { sku: "HF-MC-001", quantity: 999, trackQuantity: false },
        tags: ["podologie", "pedicure", "medical", "foot care"],
        ratings: { average: 4.9, count: 389 },
        status: "active",
        isFeatured: true,
        createdBy: podologieOwner._id,
      },
      {
        tenant: podologieStore._id,
        name: "Callus & Corn Removal",
        slug: "callus-corn-removal",
        description: "Professional removal of painful calluses and corns using specialized podiatry tools. Safe, hygienic procedure. Includes foot soak, treatment, protective padding, and prevention advice.",
        shortDescription: "Professional callus treatment",
        category: podologieCategories.medicalCare._id,
        brand: "Healthy Feet",
        images: [{ url: "https://images.unsplash.com/photo-1562322140-8baeececf3df?w=800", alt: "Callus Treatment", isPrimary: true }],
        pricing: { basePrice: 55.0, salePrice: 45.0, currency: "USD" },
        inventory: { sku: "HF-MC-002", quantity: 999, trackQuantity: false },
        tags: ["callus", "corn", "removal", "foot healing"],
        ratings: { average: 4.8, count: 267 },
        status: "active",
        isFeatured: true,
        isOnSale: true,
        createdBy: podologieOwner._id,
      },
      {
        tenant: podologieStore._id,
        name: "Cracked Heel Treatment",
        slug: "cracked-heel-treatment",
        description: "Intensive treatment for dry, cracked heels. Deep exfoliation, fissure repair, and intense hydration. Restores smooth, healthy skin. Includes home care kit for continued treatment.",
        shortDescription: "Cracked heel repair therapy",
        category: podologieCategories.medicalCare._id,
        brand: "Healthy Feet",
        images: [{ url: "https://images.unsplash.com/photo-1516585427167-9f4af9627e6c?w=800", alt: "Cracked Heel Treatment", isPrimary: true }],
        pricing: { basePrice: 65.0, currency: "USD" },
        inventory: { sku: "HF-MC-003", quantity: 999, trackQuantity: false },
        tags: ["cracked heels", "dry skin", "foot repair", "healing"],
        ratings: { average: 4.8, count: 198 },
        status: "active",
        isFeatured: true,
        createdBy: podologieOwner._id,
      },
      {
        tenant: podologieStore._id,
        name: "Ingrown Toenail Treatment",
        slug: "ingrown-toenail-treatment",
        description: "Expert care for ingrown toenails. Certified podiatrist carefully removes ingrown portion, treats affected area, applies dressing, and provides prevention guidance. Gentle, effective procedure.",
        shortDescription: "Professional ingrown nail care",
        category: podologieCategories.nailCare._id,
        brand: "Healthy Feet",
        images: [{ url: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800", alt: "Ingrown Toenail", isPrimary: true }],
        pricing: { basePrice: 85.0, currency: "USD" },
        inventory: { sku: "HF-NC-001", quantity: 999, trackQuantity: false },
        tags: ["ingrown nail", "toenail", "nail care", "treatment"],
        ratings: { average: 4.9, count: 234 },
        status: "active",
        isFeatured: true,
        createdBy: podologieOwner._id,
      },
      {
        tenant: podologieStore._id,
        name: "Fungal Nail Treatment",
        slug: "fungal-nail-treatment",
        description: "Medical treatment for fungal nail infections (onychomycosis). Includes assessment, debridement of affected nail, topical antifungal application, and treatment plan. Multiple sessions may be required.",
        shortDescription: "Fungal infection treatment",
        category: podologieCategories.nailCare._id,
        brand: "Healthy Feet",
        images: [{ url: "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=800", alt: "Fungal Treatment", isPrimary: true }],
        pricing: { basePrice: 95.0, currency: "USD" },
        inventory: { sku: "HF-NC-002", quantity: 999, trackQuantity: false },
        tags: ["fungal", "nail infection", "medical", "treatment"],
        ratings: { average: 4.7, count: 156 },
        status: "active",
        isFeatured: true,
        createdBy: podologieOwner._id,
      },
      {
        tenant: podologieStore._id,
        name: "Diabetic Foot Assessment",
        slug: "diabetic-foot-assessment",
        description: "Comprehensive foot assessment for diabetic patients. Includes circulation check, sensation testing, skin examination, nail care, and risk assessment. Essential for diabetes management and complication prevention.",
        shortDescription: "Comprehensive diabetic foot check",
        category: podologieCategories.diabeticCare._id,
        brand: "Healthy Feet",
        images: [{ url: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800", alt: "Diabetic Care", isPrimary: true }],
        pricing: { basePrice: 95.0, currency: "USD" },
        inventory: { sku: "HF-DC-001", quantity: 999, trackQuantity: false },
        tags: ["diabetic", "assessment", "foot care", "medical"],
        ratings: { average: 4.9, count: 145 },
        status: "active",
        isFeatured: true,
        createdBy: podologieOwner._id,
      },
      {
        tenant: podologieStore._id,
        name: "Diabetic Foot Care Package",
        slug: "diabetic-foot-care-package",
        description: "Complete foot care package for diabetic patients. Gentle nail trimming, careful callus reduction, moisturizing, and circulation-boosting massage. Extra attention to skin integrity and infection prevention.",
        shortDescription: "Complete diabetic foot treatment",
        category: podologieCategories.diabeticCare._id,
        brand: "Healthy Feet",
        images: [{ url: "https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=800", alt: "Diabetic Package", isPrimary: true }],
        pricing: { basePrice: 85.0, salePrice: 75.0, currency: "USD" },
        inventory: { sku: "HF-DC-002", quantity: 999, trackQuantity: false },
        tags: ["diabetic", "package", "foot care", "specialized"],
        ratings: { average: 4.9, count: 123 },
        status: "active",
        isFeatured: true,
        isOnSale: true,
        createdBy: podologieOwner._id,
      },
      {
        tenant: podologieStore._id,
        name: "Foot Reflexology",
        slug: "foot-reflexology",
        description: "Ancient healing art of foot reflexology. Pressure applied to specific zones promotes healing and relaxation throughout the body. Relieves stress, improves circulation, and enhances overall wellbeing.",
        shortDescription: "Therapeutic foot reflexology",
        category: podologieCategories.reflexology._id,
        brand: "Healthy Feet",
        images: [{ url: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800", alt: "Reflexology", isPrimary: true }],
        pricing: { basePrice: 65.0, currency: "USD" },
        inventory: { sku: "HF-RF-001", quantity: 999, trackQuantity: false },
        hasVariants: true,
        variantOptions: [{ name: "Duration", values: ["30 min", "45 min", "60 min"] }],
        tags: ["reflexology", "massage", "wellness", "relaxation"],
        ratings: { average: 4.8, count: 312 },
        status: "active",
        isFeatured: true,
        createdBy: podologieOwner._id,
      },
      {
        tenant: podologieStore._id,
        name: "Therapeutic Foot Cream",
        slug: "therapeutic-foot-cream",
        description: "Medical-grade foot cream with urea, tea tree oil, and shea butter. Deeply moisturizes, fights fungus, and repairs cracked skin. Recommended by podiatrists. 200ml jar.",
        shortDescription: "Professional foot care cream",
        category: podologieCategories.footProducts._id,
        brand: "Healthy Feet Pro",
        images: [{ url: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=800", alt: "Foot Cream", isPrimary: true }],
        pricing: { basePrice: 28.0, currency: "USD" },
        inventory: { sku: "HF-FP-001", quantity: 100, trackQuantity: true },
        tags: ["cream", "moisturizer", "foot care", "product"],
        ratings: { average: 4.8, count: 189 },
        status: "active",
        isFeatured: true,
        createdBy: podologieOwner._id,
      },
      {
        tenant: podologieStore._id,
        name: "Custom Orthotic Insoles",
        slug: "custom-orthotic-insoles",
        description: "Custom-made orthotic insoles based on foot analysis and casting. Corrects alignment, provides arch support, and relieves pain. Includes fitting consultation and follow-up adjustment.",
        shortDescription: "Custom-fitted orthotic insoles",
        category: podologieCategories.footProducts._id,
        brand: "Healthy Feet Pro",
        images: [{ url: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800", alt: "Orthotic Insoles", isPrimary: true }],
        pricing: { basePrice: 250.0, salePrice: 199.0, currency: "USD" },
        inventory: { sku: "HF-FP-002", quantity: 50, trackQuantity: true },
        tags: ["orthotics", "insoles", "custom", "foot support"],
        ratings: { average: 4.9, count: 98 },
        status: "active",
        isFeatured: true,
        isOnSale: true,
        createdBy: podologieOwner._id,
      },
    ];

    await Product.insertMany(podologieProducts);


    // ═══════════════════════════════════════════════════════════════════════
    // UPDATE STATS AND CREATE DEMO CUSTOMERS
    // ═══════════════════════════════════════════════════════════════════════
    logger.info("Updating store statistics...");

    const stores = [
      { store: groceryStore, products: 7, customers: 234 },
      { store: hairSalonStore, products: 7, customers: 342 },
      { store: massageStore, products: 8, customers: 289 },
      { store: podologieStore, products: 10, customers: 256 },
    ];

    for (const { store, products, customers } of stores) {
      await Tenant.findByIdAndUpdate(store._id, {
        "stats.totalProducts": products,
        "stats.totalCustomers": customers,
      });
    }

    // Create demo customer
    logger.info("Creating demo customers...");
    await User.create({
      email: "customer@demo.com",
      password: "Customer@123",
      firstName: "John",
      lastName: "Customer",
      role: "customer",
      tenant: groceryStore._id,
      status: "active",
      addresses: [
        {
          label: "Home",
          firstName: "John",
          lastName: "Customer",
          street: "123 Main St",
          city: "New York",
          state: "NY",
          zipCode: "10001",
          country: "US",
          phone: "+1 (555) 111-2222",
          isDefault: true,
        },
      ],
    });

    logger.info("\n");
    logger.info("═══════════════════════════════════════════════════════════════════════════════");
    logger.info("                                                                               ");
    logger.info("   DATABASE SEEDING COMPLETED SUCCESSFULLY!                                    ");
    logger.info("                                                                               ");
    logger.info("   DEMO STORES CREATED (4 Stores):                                             ");
    logger.info("   ──────────────────────────────────────────────────────────────────────────  ");
    logger.info("   1. FreshMart Grocery (fresh-mart)        - Supermarket / Grocery            ");
    logger.info("   2. Glamour Hair Studio (glamour-hair)    - Hair Salon Business              ");
    logger.info("   3. Tranquil Touch Spa (tranquil-spa)     - Massage Parlour Business         ");
    logger.info("   4. Healthy Feet Clinic (healthy-feet)    - Podologie / Foot Care Business   ");
    logger.info("                                                                               ");
    logger.info("   STORE OWNERS (All use Password: Owner@123456):                              ");
    logger.info("   owner@freshmart.com         owner@glamourhair.com                           ");
    logger.info("   owner@tranquilspa.com       owner@healthyfeet.com                           ");
    logger.info("                                                                               ");
    logger.info("   DEMO CUSTOMER:                                                              ");
    logger.info("   Email: customer@demo.com                                                    ");
    logger.info("   Password: Customer@123                                                      ");
    logger.info("                                                                               ");
    logger.info("   TOTAL PRODUCTS: 32+ products/services across all stores                     ");
    logger.info("                                                                               ");
    logger.info("═══════════════════════════════════════════════════════════════════════════════");

    process.exit(0);
  } catch (error) {
    logger.error("Seeding failed:", error);
    process.exit(1);
  }
};

seedData();
